### ISSUE TITLE
Arrows are not working after i select a date value

### ISSUE THREAD

**Issue by ivag** [YouCanBookMe/react-datetime#101]
I'm using react-datetime version - 2.3.2, and the arrows are not working after i select a date .

**Comment by simeg** [comment]
Try upgrading to 2.3.3. If that doesn't help, can you provide a more detailed step-by-step guide on how to reproduce this bug? The best would be if you could create a [codepen](http://codepen.io/) in a reproducible environment.

**Comment by ivag** [comment]
Works fine in 2.3.3. Thanks.
