### ISSUE TITLE
Calendar stays open after focus is tabbed out

### ISSUE THREAD

**Issue by andriy-kudrya-eleks** [YouCanBookMe/react-datetime#103]
Also onBlur event is not fired on tab out

**Comment by simeg** [comment]
Can this be closed? If I understand it correctly it is resolved in [this commit](https://github.com/YouCanBookMe/react-datetime/commit/9012e8199a9db78b4a9d381378cf9843ec8c1a1e).

**Comment by andriy-kudrya-eleks** [comment]
Oh, yes )
