### ISSUE TITLE
AM/PM for time selection

### ISSUE THREAD

**Issue by nirchernia** [YouCanBookMe/react-datetime#107]
Is there any way currently to make the time selection be in 12 hour time instead of 24 hour time?

Currently it looks like this: 

![screen shot 2016-07-18 at 8 47 26 am](https://cloud.githubusercontent.com/assets/7181839/16920910/59f969a4-4cc4-11e6-8eb2-af077b4b7032.png)

Can this be changed somehow? I cant seem to find anything in the docs.

**Comment by simeg** [comment]
Try setting the `timeFormat` prop to `h:mm A`. You can find more information about it in the [README](https://github.com/YouCanBookMe/react-datetime#api) under `timeFormat`.
