### ISSUE TITLE
Starting week from monday

### ISSUE THREAD

**Issue by kperwel** [YouCanBookMe/react-datetime#111]
Hi. Is it possible to select first day of the week? f.e in many countries is common to use Monday, instead of Sunday as first week day

**Comment by kperwel** [comment]
Oh, i see. First day of the week is part of moment locale configuration. Sorry for interrupting. This datepicker is great.

**Comment by MidnightP** [comment]
Appears to be not working on latest version 2.16.3

```
locale = moment.locale()

<DatePicker
	className="rdt rdt--primary"
	locale={locale}
	value={(moment @state.value)}
/>
```

![image](https://user-images.githubusercontent.com/22522186/51756085-7d545800-20c0-11e9-85d7-5fa753ac703e.png)

Any ideas?

**Comment by MidnightP** [comment]
I found out that when changing the locale of the `moment` singleton, `react-datetime` also takes that locale.  That sufficient for me. Apparently overriding the value for `react-datetime` only is more complicated, but that's fine now.

**Comment by dominiceden** [comment]
This worked for me and my calendar now starts on a Monday:

```
import moment from 'moment';
import enGb from 'moment/locale/en-gb';

<Datetime
  name="selectedDate"
  value={moment(selectedDate)}
  timeFormat={false}
  locale={moment.locale()}
  utc={false}
  dateFormat="ddd MMM Do YYYY"
  onChange={moment => {
    handleChange({
      target: {
        name: 'selectedDate',
        value: moment.format('YYYY-MM-DD'),
      },
    });
  }}
/>
```
