### ISSUE TITLE
disableOnClickOutside should be on the docs (useful for external popovers)

### ISSUE THREAD

**Issue by georgesboris** [YouCanBookMe/react-datetime#113]
Conflicts may appear when using react-datime inside another popover since the react-datetime `onClickOutside` behaviour may conflict with the same behaviour found on the popover component. 

Turns out this can be disabled by setting `disableOnClickOutside` on the component.
This setting is nowhere in the docs though.

Why would someone use react-datetime inside another popover component?
Consistency between the app components. Flexibility of using it grouped with other features...

**Comment by simeg** [comment]
Thanks @georgesboris. I updated the README.
