### ISSUE TITLE
allow a custom class on the rdtPicker

### ISSUE THREAD

**Issue by scags9876** [YouCanBookMe/react-datetime#115]
It would be great if there was a way to put some css on the rdtPicker.

Specifically, i want to add a class that will add:

```
float: right;
position: static;
```

Since I'm using this field as a filter on the right side of my screen, when the date picker is opened, the calendar goes off the screen.  I'd like the right side of the picker to align with the right side of the input.  If there was an 'additionalPickerClass' prop, i could do that easily.

**Comment by simeg** [comment]
You can use the prop `className` which adds the provided class to the outermost element (`rdt`), from there you can target the `rdtPicker` as it is a child of the `rdt` element.
