### ISSUE TITLE
Without regular <Datetime /> fromat.

### ISSUE THREAD

**Issue by sreekanth009** [YouCanBookMe/react-datetime#120]
Hi, is there a way i can use without regular <Datetime/> format.. instead of this i want to use normal <input/> and bring out the calendar.
version = 2.3.3

**Comment by simeg** [comment]
Hi Sreekanth,
I am not exactly sure what your issue is based on your description. Can you please try to explain your issue a bit more? Thanks.

**Comment by arqex** [comment]
If we don't have more info about the issue after a month I think we will be able of closing it. What do you think @simeg? when it's a good time to close a stale issue?

**Comment by simeg** [comment]
If we have asked and it's up the the other person to provide more information, then I think we can close it after a month 👍.
