### ISSUE TITLE
Would it be possible to add an arrow for the AM/PM component as well? 

### ISSUE THREAD

**Issue by glorp47** [YouCanBookMe/react-datetime#121]
That would be great for UX :)

**Comment by davidfurlong** [comment]
Can you elaborate?

**Comment by glorp47** [comment]
Well as I understand the AM/PM doesn't have an arrow underneath it which
allows you to change it, you have to manually click from 11 AM to 11 PM.
Unless I'm missing something

**Comment by davidfurlong** [comment]
Ah I see what you mean! Will look at it now

**Comment by davidfurlong** [comment]
@glorp47 implemented, see https://github.com/YouCanBookMe/react-datetime/pull/124
