### ISSUE TITLE
Is it possible to open modal for calender default on some other date instead of current one.

### ISSUE THREAD

**Issue by Divyansh1605** [YouCanBookMe/react-datetime#125]

**Comment by simeg** [comment]
No, it's not. The `value` prop has been commented out as you can see here:
https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L24

I can't find the pull request for when it got commented out, but WebStorm says it was commented out when a bug was fixed: **`Fixes timepicker not showing when dateFormat=false`**

You can always bring the prop back and create a pull request.

**Comment by Divyansh1605** [comment]
Actually i have tried something with it, onFocus i setted the value say: 18years back from now and opened the modal by open=true.
 Worked for me.
But onBlur is not called as expected,so i am not able to close the modal by open=false.

**Comment by simeg** [comment]
That's an option, sure. But it's a hacky solution and therefore not all functionality is working, as you have seen.
