### ISSUE TITLE
Increasing minutes beyond 59 doesn't increase the hour

### ISSUE THREAD

**Issue by pies** [YouCanBookMe/react-datetime#127]
In the time widget, when I increase time above 59, the minutes (correctly) switch back to 0, but the hours do not increase by one.

**Comment by simeg** [comment]
It's the same behaviour with the hours, increasing hour from 11 -> 12 doesn't affect anything else. I agree this should be fixed.

**Comment by arqex** [comment]
That behaviour is intended, I use the time picker setting the hours, then the minutes and then the seconds. If I want to set it to 11:50:50, I set 11 in the hours, and after that I would try to set the 50 pressing the decrease button for the minutes, if it changed the hours to 10 I would need to go back to the hours and set it to 11 again.

**Comment by simeg** [comment]
Thinking about it, the component is a date picker and as a user you are suppose to set the time. Thinking about it as a clock of some sort it makes sense to make the hour increment when minutes go past 59, but as a simple time selector it does not.

**Comment by simeg** [comment]
Maybe this should also be the case for switching between AM to PM? E.g. going from 11 -> 12 switches the AM/PM. To keep consistency we should decide on one approach, and I like your idea to just keep it simple.

Thoughts, @arqex?

**Comment by arqex** [comment]
I think maybe we can add a new prop for this, if the prop is "on" updating the minutes over the 59 will increase an hour, and under 0 will decrease the hour. The same would happen for seconds and hours with the AM/PM selector.

That way we can satisfy everybody and we are not including a breaking change. What do you think?

**Comment by simeg** [comment]
That solution sounds good to me.
