### ISSUE TITLE
am/pm doesn't display correctly

### ISSUE THREAD

**Issue by grigored** [YouCanBookMe/react-datetime#133]
see the attached image, which can be replicated on the sample codepen in the readme http://codepen.io/simeg/pen/mEmQmP
<img width="272" alt="screen shot 2016-09-06 at 2 06 24 am" src="https://cloud.githubusercontent.com/assets/12827406/18258093/ea3178a6-73d7-11e6-8fb3-2102d84fc9fa.png">

**Comment by simeg** [comment]
Thanks. I just noticed this as well, I'm investigating 🔬

**Comment by simeg** [comment]
This is because of the following commit: https://github.com/YouCanBookMe/react-datetime/commit/79e319bb213a10d146c9ecf054199cbe52e4c712

I'm guessing the flow is broken and the element is inserted in the DOM at an too early stage. I will look further into this later (if no one is quicker than me).

**Comment by simeg** [comment]
This was fixed as the version was bumped. The CSS is now in sync with the JS code. Thanks @grigored.
