### ISSUE TITLE
Preventing the selection of date and times in the past

### ISSUE THREAD

**Issue by tsnolan23** [YouCanBookMe/react-datetime#136]
Is it possible to prevent the picking of dates and times that have already past? We only want to allow the selection of future dates.

**Comment by tsnolan23** [comment]
I apologize, I see this is in the documentation

**Comment by omidfi** [comment]
I couldn't find it in documentation quickly and ended up here, maybe it can be improved, I searched for "past" on the page.

**Comment by simeg** [comment]
@omidfi Hi,

The prop you are looking for is called `isValidDate`. Thanks for the feedback, I'll re-phrase the example part for `isValidDate` to include that word.

**Comment by omidfi** [comment]
You are an amazing person :)
