### ISSUE TITLE
When date is null, "NaN" is displayed.

### ISSUE THREAD

**Issue by JimBarrows** [YouCanBookMe/react-datetime#140]
I'm passing in a moment, that was created from a null date.  The component responds with "NaN", and should respond with a blank input box.

**Comment by simeg** [comment]
Hi @JimBarrows,

In what prop are you passing in the moment object to get this result?

**Comment by JimBarrows** [comment]
The thruValue is the moment wrapping a null.
`<DatePicker id={this.thruName} name={this.thruName} value={thruValue}
							            onChange={this.thruChange.bind(this)} dateFormat={dateFormat} timeFormat={false}/>`

**Comment by simeg** [comment]
@JimBarrows this should now be fixed. Wait until next release and then please come back if the problem remains, thanks.

**Comment by vsamiev** [comment]
@simeg i see bump version in repo, when do you plan to publish this update to npm ?

**Comment by simeg** [comment]
@vsamiev I tried to bump it in commit 3fdcb759237f2ed168b694bb46bdbb7d0d7620a8, I thought I could just bump the version in `package.json` and npm would magically find out about it. Turns out I was wrong 😝 I've contacted @arqex about it, he knows what to do! Just wait a bit more. Thanks.

**Comment by arqex** [comment]
Sorry for the delay. New version published ;)

**Comment by vsamiev** [comment]
@arqex 
just updated, there are missing files in package   :'(
/node_modules/react-datetime/css/react-datetime.css
/node_modules/react-datetime/src/DaysView.js
/node_modules/react-datetime/src/MonthsView.js
/node_modules/react-datetime/src/YearsView.js
/node_modules/react-datetime/src/TimeView.js
/node_modules/react-datetime/src/onClickOutside.js

**Comment by simeg** [comment]
@vsamiev see #176.
