### ISSUE TITLE
Use inline styling

### ISSUE THREAD

**Issue by simeg** [YouCanBookMe/react-datetime#142]
To make sure everyone gets the styling of the component (without using webpack loaders and what not) we should use inline styling. See discussions in issue #132.

We should do this according to **best practice**, and we should also consider how a developer could **override the default styling with custom styling**. How can we make it simple for everyone?

**Comment by layneanderson** [comment]
I like the method of using an Object to overwrite styles like done in https://github.com/marcio/react-skylight (see demo page).  I found it very easy to use, however, I haven't played with it enough to see what limitations there are.

**Comment by simeg** [comment]
@layneanderson I could not find anything in the demo page, but in the `src/` I found [an approach I really like](https://github.com/marcio/react-skylight/blob/master/src/skylightstateless.jsx#L20) (maybe this is what you are referring to). 

I like it because you are not mutating the styles state, you can extract the styling to a separate file and it's very obvious what you are doing. Nice find 👍.

**Comment by layneanderson** [comment]
@simeg yes, that's essentially what I was referring to.  The demo page (http://marcio.github.io/react-skylight/) shows a few examples of how it's used.  I like that all the overrides can be kept in a nice neat Object.  :smiley:

**Comment by simeg** [comment]
@layneanderson oh you could scroll down haha, totally missed that. I see now what you mean, it looks very nice ☀️.

So a problem is that probably all CSS classes can be removed, but that breaks everything for everyone. I'm guessing a lot of people use their own CSS as the default one is rather minimal. How do we deal with this? @arqex thoughts?

**Comment by tkh44** [comment]
You don't have to remove the styles.  You could just pass the relevant style object to each component.  Users not wanting to use the css files just won't import them and the style object will take precedence anyways.

**Comment by rroslaniec** [comment]
Maybe consider to use https://github.com/Khan/aphrodite?
You can have a css for each components and pass new via props.
Most ppl uses css with webpack (postcss or smth else) - it could be work
