### ISSUE TITLE
[question] keyboard Navigation

### ISSUE THREAD

**Issue by TianyiXia** [YouCanBookMe/react-datetime#145]
Hi, just wondering if there is way to do keyboard navigation for the date picker? Like using left/right key to navigate date? Thanks.

**Comment by simeg** [comment]
Hi, thanks for your question.

It's not possible to do this right now. Personally I don't think this is a prioritised issue that should be fixed immediately, but can you elaborate on your use case?

Thanks.

**Comment by TianyiXia** [comment]
im trying to automate setting

**Comment by wullaski** [comment]
I know this is closed but I'd also like to have keyboard accessibility added. It a pain but it would be a nice added feature. If I have time maybe I'll create a pull request.

Thanks for the great component.

**Comment by mcorteel** [comment]
I also think that this is important.
I'm using this component in tables that need to be filled very quickly by the user so keyboard navigation is a must have. For example:
* Input a product (in a typeahead), hit `tab`
* Input product packaging (in a select), hit `tab`
* Input the quantity received, hit `tab`
* Input expiration date (there, the user has to use the mouse or type the whole date by hand)
* etc.

This can be pretty frustrating!

Anyway, thanks for a great component! 🥇
