### ISSUE TITLE
date only to time only update on mode change doesn't work

### ISSUE THREAD

**Issue by jpatel3** [YouCanBookMe/react-datetime#155]
I have parent dropdown which decides if component needs to be date only or time only. Once the date only control is rendered, changing the parent to time only calls the render again but doesn't refresh the component. On click of the text box, I still get date selection. Sometimes, it does get the time control, but the behavior is not consistent. 

Is there any way to force refresh of HTML? or am I missing anything?

**Comment by simeg** [comment]
Hey @jpatel3.

Could you please provide a code demo for this? It would make it a lot easier.

**Comment by simeg** [comment]
Closing this as there hasn't been any activity for over a month. Re-open if you're still having issues. Thanks.

**Comment by jpatel3** [comment]
@simeg Sorry for not responding to this earlier. Here is the example code - 

```
    if ( this.props.mode == 'date' ) {
      timeFormat = false;
    } else if (this.props.mode == 'time' ) {
      dateFormat = false;
    }

    if( typeof(leftNumber) === 'undefined' || typeof(rightNumber) === 'undefined')
    {
      return (
        <div className="numericComponent">
          <div>No valid numeric value for the attribute.</div>
        </div>
      );
    } else {
      return (
        <div className="numericComponent">
          <div className="headText">Filter Range:</div>

          <div className="numericaField">
            <div className="rangeLabel">Min:</div>
            <Datetime value={leftNumber}
            className="leftNumber"
            dateFormat={dateFormat}
            timeFormat={timeFormat}
            onChange={this.onChange.bind(this, 'leftNumber')}
            onBlur={this.onBlur.bind(this, 'leftNumber')} />

          </div>
          <div className="numericaField">
            <div className="rangeLabel">Max:</div>
            <Datetime value={rightNumber}
            className="rightNumber"
            dateFormat={dateFormat}
            timeFormat={timeFormat}
            onChange={this.onChange.bind(this, 'rightNumber')}
            onBlur={this.onBlur.bind(this, 'rightNumber')} />
          </div>
        </div>
      );
    }
```

In above default value for `dateFormat` and `timeFormat` is true. The type is passed by the parent component. However, upon receiving different props.mode, it doesn't change the DateTime picker. 

Let me know if any solution I can try out.

**Comment by layneanderson** [comment]
Hi @jpatel3 ,

I think what you are trying to do is achieved by viewMode.  So instead of changing dateFormat or timeFormat you would change the viewMode prop to either 'days' or 'time'.

Incidentally it wouldn't have worked back in September, but has since been fixed.  (see issue #202)

Regards,

Layne

**Comment by jpatel3** [comment]
@layneanderson I'll try out. For now, I have tried adding a key to the component to make sure it does a hard refresh, and it works fine with that change. but will try out `viewMode`.

**Comment by nonconformatevi** [comment]
Hi @layneanderson ,
thanks for your suggestion. I had a similar problem and I solved it by settings viewMode parameter.

Regards,
Daniele
