### ISSUE TITLE
Is there a way to select the date/time in hover selection (not input) ? 

### ISSUE THREAD

**Issue by mikethejet** [YouCanBookMe/react-datetime#156]
For example when i know that most of events start about 18:00 i want to predefine the selectable time in time "combo" (not in input, only predefine the time selection)
Any help ? Any method how to set it?

![times](https://cloud.githubusercontent.com/assets/2683571/19105468/5ad265fe-8ae2-11e6-9858-d450467d2cf0.jpeg)

**Comment by simeg** [comment]
Hi @mikethejet. Looking at the API I do not think this is possible, but I do think it's a good idea to be able to set the predefined time. A problem with that is that you can also set `timeFormat` and `timeConstraints`, and the component would have to keep track of the prioritisation. 

If you feel like you want to create a PR for this I'd be happy to review it.
