### ISSUE TITLE
timeFormat setting does not work as expected

### ISSUE THREAD

**Issue by huyttq** [YouCanBookMe/react-datetime#157]
Reproducing bug [here](http://codepen.io/anon/pen/yaoELg)

**Comment by gferreri** [comment]
try `<Datetime timeFormat={false}/>` instead of `<Datetime timeFormat="false"/>`

**Comment by simeg** [comment]
Hi @huyttq. The `timeFormat` wants either a `string` or a `boolean`, I think you are trying to input a `boolean` but you are inputting a `string`. @gferreri has the solution (thanks!).
