### ISSUE TITLE
componentWillReceiveProps() is not honouring old state

### ISSUE THREAD

**Issue by gvelo** [YouCanBookMe/react-datetime#163]
when `currentView = 'days'` and `update.open === undefined` , if the datepicker state was `open`, it should remain `open`. In other words, when `currentView = 'days` and the parent component re render executing datepicker `componentWillReceiveProps()`, datepicker will close.

```
if ( update.open === undefined ){
            if ( this.props.closeOnSelect && this.state.currentView !== 'time' ){
                update.open = false;
            }
            else {
                update.open = this.state.open;
            }
        }
```

**Comment by simeg** [comment]
This PR was reverted due to creating other bugs in version 2.8.6. We will have to figure this out in another way.
