### ISSUE TITLE
dist build is broken for requirejs

### ISSUE THREAD

**Issue by marianoguerra** [YouCanBookMe/react-datetime#17]
line https://github.com/arqex/react-datetime/blob/master/dist/react-datetime.js#L10

should be

    define(["react", "moment"], factory);

same for this line https://github.com/arqex/react-datetime/blob/master/dist/react-datetime.js#L12
undefined should be replaced for lib names.

I don't know webpack to propose a fix, also tried to build it locally and couldn't, the following error happens:

    Error: Path doesn't exist '/home/mariano/soft/react-datetime/react-datetime.js'

to achieve that I had to run gulp manually since npm build seems to be configured to only work on windows.

**Comment by halkeye** [comment]
I think I figured it out, `gulp.src('./Datetime.js')` should really be `gulp.src('./DateTime.js')`

I ended up rewriting that anyways
https://github.com/halkeye/react-datetime/blob/master/gulpfile.js

**Comment by simeg** [comment]
Closing this as you can run the `build` task as both a Windows and Mac user now (`npm run build:win`/`npm run build:mac`).
