### ISSUE TITLE
CSS file not included in 2.6.1 npm package

### ISSUE THREAD

**Issue by MilosRasic** [YouCanBookMe/react-datetime#176]
See title.

2.6.0: http://i.imgur.com/GGp4emK.png

2.6.1: http://i.imgur.com/SW7aL83.png

You broke the Internet.

**Comment by LKay** [comment]
Looks like the package was incorrectly published to npm and the compiled files were not included.

**Comment by simeg** [comment]
This is most likely because of 75c558e8e1d659e134e85aadd3f818bebd5ae12c. I will publish a possible fix, bump the version and ask @arqex to bump the npm version again. Sorry for the inconvenience.

**Comment by simeg** [comment]
@MilosRasic @LKay @mattiasnordqvist @J-F-Liu @vsamiev can you update to 2.6.2 and see if it works? It seems to work for me.

**Comment by vsamiev** [comment]
i confirm that it works 👍

**Comment by J-F-Liu** [comment]
confirmed, thanks.

**Comment by mattiasnordqvist** [comment]
typings are rollin' again :ok_hand:
