### ISSUE TITLE
onFocus and onBlur are acting weird

### ISSUE THREAD

**Issue by damianprzygodzki** [YouCanBookMe/react-datetime#183]
I have tried to control picker by myself, because i had to add third way to open/close the calendar.

So i've followed the docs and connected prop "open" to my state, onFocus was setting the prop open:true, but calendar didn't appear.

The same with onBlur, when i tried change value open onBlur, there is no change.

EDIT:

After 5h of looking for proper way to control open prop i have found the workaround.

```
class DatePicker extends Component {
    constructor(props) {
        super(props);

        this.state = {
            open: undefined
        }
    }

    handleFocus = () => {
        this.setState(Object.assign({}, this.state, {
            open: true
        }));
    }

    handleClose = () => {
        this.setState(Object.assign({}, this.state, {
            open: false
        }));
    }

    renderDay = (props, currentDate) => {
        return (
            <td
                {...props}
                onDoubleClick={this.handleClose}
            >
                {currentDate.date()}
            </td>
        );
    }

    render() {
        const {open} = this.state;
        return (<Datetime
            className={open && "rdtOpen"}
            onFocus={this.handleFocus}
            onBlur={this.handleClose}
            renderDay={this.renderDay}
            {...this.props}
        />)
    }
}
```

It is whole example of my wrapper - i just wanted to hide dropdown when doubleClick on day.

**Comment by damianprzygodzki** [comment]
After 5h of looking for proper way to control open prop i have found the workaround.

```
render() {
        const {open} = this.state;
        return (<Datetime
            className={open && "rdtOpen"}
            onFocus={this.handleFocus}
            renderDay={this.renderDay}
            {...this.props}
        />)
    }
```

**Comment by hazboun** [comment]
facing the same. Noticed that onBlur doesn't fire at all!

**Comment by hazboun** [comment]
onBlur and onFocus must be passed within inputProps like this:

return (<Datetime
            className={open && "rdtOpen"}
            inputProps:{
                onFocus: this.handleFocus,
                onBlur: this.handleClose
             }
            renderDay={this.renderDay}
            {...this.props}
        />)

**Comment by damianprzygodzki** [comment]
So i believe it is a issue of documentation, right? OnFocus&OnBlur are with inputProps on the same level in table describing properties.

**Comment by simeg** [comment]
@damianprzygodzki I'll do some investigation tonight when I get home about this. Sounds fishy. It should definitely specify in the docs if this is how it works.

@hazboun thanks a lot!

**Comment by damianprzygodzki** [comment]
@simeg thanks for that.

Some new clues found after lot of investigation.

`onBlur` is working (outside the inputProps) but there is no `date` parameter described in doc. `onBlur` and `onFocus` in the inputProps do not return the `date` described in doc.

**Comment by simeg** [comment]
@damianprzygodzki does merging #164 affect this issue you are having? Besides the documentation potentially being wrong (I'll have to investigate on that).

**Comment by damianprzygodzki** [comment]
@simeg yeah, now it is working stable and (watch out!) properly with documentation! So i think what @hazboun said is true - but completely different case - these are native input events.
