### ISSUE TITLE
dist files have extra weight due to source maps

### ISSUE THREAD

**Issue by Symbiatch** [YouCanBookMe/react-datetime#185]
The files in the dist folder have loads of extra weight. With 15k of code you get 78k in "normal" and 91k in "minified." Quite suboptimal. Looks like the source mapping is put into the files and that makes them very big. Might be worth it to change settings so the files could be used as-is without causing a huge overhead to load.

**Comment by simeg** [comment]
@Symbiatch thanks for bringing this up. I'll look into this as soon as I can.

**Comment by simeg** [comment]
I fixed this (by reverting the commit adding the source-map file, it was messing up the build pipeline somehow), so when the creator of this package (who has access to the npm repo) publishes it to npm then you can download it it. It shouldn't take more than a day or two for him to do that. 

I'll close this for now but if you experience anything wrong with 2.7.0 feel free to open it.
