### ISSUE TITLE
isValidDate is hiding current month and year

### ISSUE THREAD

**Issue by simeg** [YouCanBookMe/react-datetime#192]
1) [Look at this demo](http://codepen.io/simeg/pen/XNNYJg)
2) Notice the current month (November right now)
3) Notice the current year (2016 right now)
4) Click "November 2016" to go to month view
5) November is a disabled option **<- BUG**
6) Click "2016" to go to year view
7) 2016 is a disabled option **<- BUG**

As the functionality of actually validating months and year was introduced pretty recently, I'm guessing it was [this commit](c306f2fcc9b08aef38a246f94949826965ff66c1) that caused it.

@michelre do you feel like looking into it? :)

**Comment by michelre** [comment]
Thanks for your feedback. I'll check this out this week end! :)
