### ISSUE TITLE
v2.7.2 broken on npm

### ISSUE THREAD

**Issue by levity** [YouCanBookMe/react-datetime#194]
I'm getting a 404 error for v2.7.2 when I try to install it from npm.  I know you don't run the registries but I figured you'd want to know about this if you don't already.

**Comment by simeg** [comment]
@levity thanks I'll take a look. I think I broke it..

**Comment by simeg** [comment]
@levity is it working for you now? It's working for me locally and for Travis CI as well.

**Comment by levity** [comment]
Yep, looks good here.
