### ISSUE TITLE
Getting a 404 error with version v2.7.4

### ISSUE THREAD

**Issue by StevenIseki** [YouCanBookMe/react-datetime#197]
Similar to [this](https://github.com/YouCanBookMe/react-datetime/issues/194) issue, but for the recently published version 2.7.4.

**Comment by vipinlahoti** [comment]
Same error for me too:
CLI>
npm ERR! fetch failed https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.4.tgz
npm ERR! fetch failed https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.4.tgz
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\vipinl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\vipinl\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.2_1\\mt-os.windows.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-datetime"
npm ERR! node v4.6.1
npm ERR! npm  v3.10.9

**Comment by StevenIseki** [comment]
If you want a temporary fix, just use `2.7.2` for the time being.

**Comment by eigenmannmartin** [comment]
`2.7.3` does work for me.

**Comment by Toxblh** [comment]
I have this problem too...

**Comment by arqex** [comment]
Hey guys, that's weird, it seems that something failed in the deployment to npm. I have just bumped the version and publish the package again.

**Comment by arqex** [comment]
https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.5.tgz

Is working for me, but guess what..

https://registry.npmjs.org/react-datetime/-/react-datetime-2.7.4.tgz

it's also working for me now ¬¬

Can you guys confirm?

**Comment by vipinlahoti** [comment]
2.7.4 is working now.

**Comment by Toxblh** [comment]
All good, thanks!

**Comment by simeg** [comment]
Weird.. I didn't get any errors when publishing. I'm working through a VPN most of the time, next time I wont do that.

**Comment by arqex** [comment]
I think it was a temporary npm's failure. I didn't do antything to fix 2.7.4 and it seems to work now.
