### ISSUE TITLE
Is there option to reduce timepicker width separately?

### ISSUE THREAD

**Issue by greenais** [YouCanBookMe/react-datetime#199]
While datepicker seems quite relevant to its days grid content, timepicker looks too wide with a lot of blank space around actual pickers.
To my understanding in `react-datetime.css` provided one width is set for both - datepicker and timepicker.
Is there any way to reduce timepicker width alone in order to make it more reasonable?

**Comment by simeg** [comment]
Hi @greenais. What you are asking for is not supported out of the box right now. I am trying to think of ways you could do it without modifying the logic, but I can't think of anything right now, sorry.
