### ISSUE TITLE
Reset value

### ISSUE THREAD

**Issue by louisotto** [YouCanBookMe/react-datetime#201]
Hi,

I'm currently using a <Datetime/> component inside a html form element with classname `addItem`, once the form has submitted I process it and then run `this.refs.addItem.reset();` which correctly resets all form elements except the Datetime one, do you have an idea how to reset it alongside the rest of the form elements?

**Comment by simeg** [comment]
Hi @louisotto.

I do not know off the top of my head, but one idea is to look through other issues mentioning `refs`. Here's a link: https://github.com/YouCanBookMe/react-datetime/issues?utf8=%E2%9C%93&q=is%3Aissue%20refs

Please let me know how it goes.

**Comment by louisotto** [comment]
Couldn't tackle it directly, but here's my workaround in case anyone else asks or you wish to document its method:

Form submits and two events fire:
1) this.form.reset();
2) state items populated by form inputs are cleared.

So we add the following props to Datetime:

value={this.state.date}
onChange={(data) => this.setState({date: Datetime.moment(data).format("DD/MM/YY")})}

That way when the form submission is complete, the state object created is clear, which resets the initial value.

Cheers man

**Comment by simeg** [comment]
I'm glad you were able to solve it, and thanks for posting your solution.
