### ISSUE TITLE
Timepicker not showing the value passed to Datetime component

### ISSUE THREAD

**Issue by tuanna1601** [YouCanBookMe/react-datetime#204]
Hi everyone,

I passed the time value, for example `value={this.props.time}` into the `<Datetime/>` component with prop `dateFormat={false}`, but when I clicked into the input box to choose another time, the timepicker always shows 12:00 AM. Since I'm using Redux and it re-renders the component everytime I maked a change to the state tree through `onChange` function so I always stuck at 12:00 AM. 
Is there any way to make the timepicker to show the value I passed into it?

**Comment by tuanna1601** [comment]
I've found out the problem, I was passing the time in wrong format (the time was in "hh:mm" format), but I set `timeFormat="hh:mm A"` that's why `<Datetime/>` couldn't display it properly.

**Comment by foodaka** [comment]
can u show more code, im having the same issue
