### ISSUE TITLE
[Request] Wrap existing input controls

### ISSUE THREAD

**Issue by BrandonBoone** [YouCanBookMe/react-datetime#205]
I would like to propose an enhancement that allows react-datetime's functionality to be added to **existing** input controls.

For Example, if I wanted to merge the functionality of [react-input-mask](https://github.com/sanniassin/react-input-mask) with react-datetime I would imagine the following syntax.

*Note: Everything below is pseudo code*

```jsx
import DateTime from 'react-datetime';
import InputElement from 'react-input-mask';

const MaskedTime = () => (
  <DateTime
    timeFormat={false}
    dateFormat="MM/DD/YYYY"
    viewMode="days"
  >
    <InputElement
      mask="99/99/9999"
      placeholder="'DOB"
    />
  </DateTime>
);
```

Another benefit is that you would, potentially, no longer need to accept `inputProps` as users could provide them directly.

```jsx
import DateTime from 'react-datetime';

const PlaceHolderDateTime = ({ placeholder }) => (
  <DateTime
    timeFormat={false}
    dateFormat="MM/DD/YYYY"
    viewMode="days"
  >
    <input
      type="text"
      placeholder={placeholder}
    />
  </DateTime>
);
```

A different option might be to provide a [Higher Order Component](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.iz1zhcua9) to enhance an existing input with DateTime functionality. Though admittedly, I'm not entirely sure how this would play out in detail as I've not built an HOC like this myself.

```jsx
// This is just a shell derived from the linked article
function DateTimeHoc(WrappedComponent) {
  class PP extends React.Component {
    constructor(props) {
      super(props)
      this.state = {
        inputValue: ''
      };
      this.onInputChange= this.onInputChange.bind(this);
    }
    onInputChange(e) {
      // your input changed logic
      this.setState({
        inputValue: event.target.value
      });
    }
    render() {
      const newProps = {
        name: {
          value: this.state.inputValue,
          onChange: this.onInputChange
        }
      };
      return <WrappedComponent {...this.props} {...newProps}/>;
    }
  }
  
  var nof = function(){};
  PP.defaultProps = {
    className: '',
    defaultValue: '',
    inputProps: {},
    input: true,
    onFocus: nof,
    onBlur: nof,
    onChange: nof,
    timeFormat: true,
    // etc.
  };
  return PP;
}

const InputElementDateTime = DateTimeHoc(InputElement);

// later on

<InputElementDateTime
  placeholder="DOB"
  timeFormat={false}
  dateFormat="MM/DD/YYYY"
  viewMode="days"
  mask="99/99/9999"
>

```

Of course react-datetime could be enhanced to support more features as built in options, but I think something like the above examples would provide maximum flexibility.

**Comment by simeg** [comment]
Hi @BrandonBoone. Thanks for your suggestion!

We are adding support for this in V3, you can see more about the probable implementation details here: #153 

Great suggestion, it will indeed make things easier for people.
