### ISSUE TITLE
Pass an event instance to onChange handler. 

### ISSUE THREAD

**Issue by PashaKoval** [YouCanBookMe/react-datetime#210]
I have a problem in case when I need additional arguments(attributes) from input field, not only date.
I propose pass an event instance to onChange handler. It will look like 
```
...
onChange = (event, date) => {
    someAttr = event.target.getAttribute('data-id');
...
};
...
```
Maybe there's another ability to get attributes from input?

**Comment by simeg** [comment]
@PashaKoval You can use the `inputProps` to use the attributes for the input field. 

`<datetime inputProps={{onChange: ev => console.log('Do whatever', ev) }} />`

Does this solve your problem?

**Comment by PashaKoval** [comment]
@simeg , yes, I've solved my problem with help of your tip. Thanks a lot.
