### ISSUE TITLE
Can we have an attribute to reset viewMode when reopening datetime modal

### ISSUE THREAD

**Issue by francischew** [YouCanBookMe/react-datetime#217]
Can we have an attribute to reset viewMode when reopening datetime modal?

Scenario:
1) used viewMode="years" for react-datetime component
2) select a date/time on react-datetime modal
    - datetime modal opens up with "years" as the default view
    - once date/time selected, modal closes
3) reopen the modal again
   - datetime modal opens up to where it left off - on selecting the time even though the viewMode="years"

Is there a way for the datetime modal to reset itself in "years" mode when reopening the datetime modal without a page refresh?

**Comment by layneanderson** [comment]
I know this would be an unwanted feature/change for me.  It is possible to do though.  The code change to do it is in my first commit in my Pull request #206.  (commit 3e69e4ef5275dc3616f5ff6c838a3b7d02a98f8d)).  This what I had to correct to make the PR compliant with normal functioning of this component.

**Comment by simeg** [comment]
@francischew Now that #206 is merged, can you solve your issue?
