### ISSUE TITLE
Custom style form input.

### ISSUE THREAD

**Issue by Extra-lightwill** [YouCanBookMe/react-datetime#218]
How do you adjust the styling of the input (e.g. the blue border) and replace with your own styles?

Seems like an silly question, but I can't figure out how to change this..

**Comment by simeg** [comment]
Hi @Extra-lightwill. 

There's multiple ways to do this, the most straight forward would be to not use any of the CSS that comes with this component. Or you can [specify your own CSS rules with higher specificity](https://css-tricks.com/specifics-on-css-specificity/) to overrule the CSS provided with this component.

Let me know if you need more information. Thanks.
