### ISSUE TITLE
Access value of input field

### ISSUE THREAD

**Issue by thientran1707** [YouCanBookMe/react-datetime#219]
How can I set the value of input field manually? since sometimes if the value is not valid, i would like to reset it to previous valid one

**Comment by simeg** [comment]
Hi @thientran1707. You can use the `value` prop to manually set the value of the component. Hope it solves your issue. [Here's more information about the API](https://github.com/YouCanBookMe/react-datetime#api).

**Comment by arqex** [comment]
So good to have you aboard @layneanderson  :)
