### ISSUE TITLE
timeFormat not applied

### ISSUE THREAD

**Issue by martinvondracek** [YouCanBookMe/react-datetime#220]
when I put custom time format, the format is applied in input field but is not applied in timepicker dropdown

`<Datetime dateFormat={false} timeFormat={'hh:mm a'} viewMode={'time'} />`

demo [here ](http://codepen.io/anon/pen/Mbxpad)

![timepicker](https://cloud.githubusercontent.com/assets/12466820/21360449/cbff3b4c-c694-11e6-9d24-449bdb5129d8.png)

**Comment by simeg** [comment]
Hi @martinvondracek. If you change the `timeFormat` string to `'hh:mm A'` - does it solve your issue?

**Comment by martinvondracek** [comment]
Hi @simeg, yes it works with 'hh:mm A' but unfortunately I need with small 'a' - 'h:mm a'

**Comment by simeg** [comment]
This seems to be a bug, looking into it.

**Comment by simeg** [comment]
@martinvondracek this has now been fixed with the following commit: https://github.com/YouCanBookMe/react-datetime/commit/cf1e721e0d7c69b5ce55978c213ef463ab477ebc

The bug fix is published in version 2.8.1. Thanks.
