### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by olegreznichenko** [YouCanBookMe/react-datetime#223]
Hello! When adding value and then edit date in input, date not update
[example](http://codepen.io/Nonlimit/pen/BQbgqZ)

**Comment by simeg** [comment]
Hi @olegreznichenko. If you want to use a placeholder for the form you can use the `inputProps` prop like this:

`<datetime inputProps={{ placeholder: 'This is the placeholder' }} />`

Hope this solves your problem.

**Comment by olegreznichenko** [comment]
My problem solved prop `defaultValue`. thx for quick feedback :)

**Comment by ron766** [comment]
Not working 
          inputProps={{ placeholder: 'demo...', disabled: false }}
          defaultValue="def"
Please advise
