### ISSUE TITLE
Is it possible to open the datetime picker from an Icon

### ISSUE THREAD

**Issue by halis** [YouCanBookMe/react-datetime#226]
I want to have a calendar icon and when I click on it I want to show the datetime picker.
Then I can plug into onChange and use the value as needed.

I tried setting `input: false` and `open: false`
The idea being that I could use Redux to drive the open field which would show/hide the datetime picker.

But after a cursory test, this does not seem to be the current behavior. When I update `open` to be `true` the picker never opens.

**Comment by halis** [comment]
I can definitely get it to open with a janky jQuery hack but if I do that then I will probably have to do another hack to get the close to work properly (like if you click anywhere else) and I don't know if I'll be able to look at myself in the mirror if I do that.

**Comment by simeg** [comment]
Hi @halis,

Two things:
1) The current `open` prop is not working as it should, so if I were you I'd just not use it right now.
2) See #153, there's a suggestion (which will go into V3 of this component) that will probably resolve your issue

So up until then, maybe use your jQuery hack if you really need this functionality. Sorry for not being of any bigger help.
