### ISSUE TITLE
when viewMode is months, the date-picker always highlight the 12 month

### ISSUE THREAD

**Issue by soulcm** [YouCanBookMe/react-datetime#233]
When set viewMode as months, whatever month I selected and open the date-picker again, the date-picker always highlight the 12 month.Below is screenshot.
![qq 20170104121216](https://cloud.githubusercontent.com/assets/5706155/21631516/11e853d0-d277-11e6-8512-1d508b913d78.png)
![qq 20170104121223](https://cloud.githubusercontent.com/assets/5706155/21631517/13025c16-d277-11e6-93fa-bdbf1619e9b7.png)

**Comment by eliezedeck** [comment]
I **confirm** this bug. Same exact problem for me.

**Comment by simeg** [comment]
Hi @soulcm,

Yes, I just noticed this my self today actually. Been trying to hunt it down but couldn't find what's wrong, will continue looking when I have time.

**Comment by soulcm** [comment]
@simeg ok, thanks for your attention

**Comment by elkinjosetm** [comment]
+1 I have the same issue. I can only select a date on first time you open the picker, after that, if you change to year view, and you try to select another month, the datepicker closes right away, and after that, I'm unable to keep using the picker, always closes. And stay at year view with december month selected.

**Comment by arnriu** [comment]
https://github.com/YouCanBookMe/react-datetime/pull/293

**Comment by danielrob** [comment]
For me this was fixed on 2.9.0 🎉 !
