### ISSUE TITLE
defaultValue doesn't affect time

### ISSUE THREAD

**Issue by redbaron76** [YouCanBookMe/react-datetime#241]
Isn't possible to set current time as the default time?
It always starts at 00:00.

**Comment by simeg** [comment]
Hi @redbaron76.

Yes, by setting `defaultValue` to a valid date value you can specify both the date and time. [Here's an example.](http://codepen.io/simeg/pen/vgNNzy)

**Comment by redbaron76** [comment]
Ok, thanks. But the question is: being `new Date()` the default datetime value, why doesn't it set the time too as it already does for the date?

**Comment by simeg** [comment]
That sounds weird, how can you tell that it's not setting the time value? I mean how do you look at the default value without changing it?
