### ISSUE TITLE
Current Year Not Selectable in Year View 

### ISSUE THREAD

**Issue by layneanderson** [YouCanBookMe/react-datetime#243]
With `validDate` set to not allow future dates if the user backs out to year view, 2017 is disabled and not selectable.

_Additional Info_
A user workaround is available by choosing 2016 and then using the arrow (>) to increment year to 2017.

**Comment by simeg** [comment]
Thanks for notifying. It's probably a duplicate of this issue: https://github.com/YouCanBookMe/react-datetime/issues/192
