### ISSUE TITLE
How re-render component on dynamically change locale parameter?

### ISSUE THREAD

**Issue by clairekh** [YouCanBookMe/react-datetime#250]
Hi! I need some help. How I can re-render component  when my locale has changed dynamically?

I use `<Datetime locale={ locale } ref="date" />` in parents component, where I get locale from store (I use redux). So after change locale I need re-render child `Datetime` component. How can I do this?

**Comment by layneanderson** [comment]
Hi @clairekh ,

There is currently an open issue on this.  See #126 . I _might_ look into fixing it next week.

Regards,

Layne

**Comment by clairekh** [comment]
@layneanderson, thank you for help!

**Comment by simeg** [comment]
Hey @clairekh. I'll close this and we can track this bug in #126 (Thanks @layneanderson!).
