### ISSUE TITLE
Autofocus input field issue

### ISSUE THREAD

**Issue by nicollehelgers** [YouCanBookMe/react-datetime#253]
### I'm Submitting a ...

```
[x] Bug report
[x] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Insert a new record (the record is a row of a datagrid with input/form fields)
2. The input field should automatically be in focus, when the record is opened, but it is not.

The issue is that this standard React feature is not working in the component, the user has to click on the input fields again to set the date.

### Expected Results
The autofocus feature of React should be active when a new record/row is opened.

### Actual Results
The autofocus feature of React is not working or not activated. 

### Minimal Reproduction of the Problem
```js
const Row = require( 'react-bootstrap' ).Row;
const DateTime = require( 'react-datetime' );

<Row>
    <div className="col-xs-7 col-md-6">                      
        <DateTime /> 
    </div>
</Row>
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
- suggestion how to fix: find out why the React feature autofocus on input fields is not working in the component and activate it again.

**Comment by byrondevonwall** [comment]
Alternately, would it be possible to update `inputProps` to accept `ref` so that it can be targeted with `componentDidMount()` or `componentDidUpdate()` by passing `this.refs.yourinputref.focus()` to either?

**Comment by nicollehelgers** [comment]
_Thanks, eventually this is working for me:_

inputProps={{
                            autoFocus:props.hasFocus
                        }}

hasFocus: React.PropTypes.bool

**Comment by byrondevonwall** [comment]
Thanks!

I'm surprised that `inputProps` accepts `autoFocus` but not `ref`

**Comment by simeg** [comment]
@nicollehelgers Nice to see you found a solution, and thanks for posting the solution.

@byrondevonwall `inputProps` does not handle any provided keys differently, so it does accept `ref` - it accepts anything.
