### ISSUE TITLE
Update documentation in dateFormat

### ISSUE THREAD

**Issue by mieryn** [YouCanBookMe/react-datetime#256]
Sorry, no template for this is a small request only.

I didn't find a mention that leaving out days or month and days on the dateFormat makes the DateTimePicker a month picker or a year picker. Maybe it should be taken for granted but I ended up reading the code to figure this out. Thought I needed to implement it myself :)

**Comment by simeg** [comment]
Hi @mieryn.

We have the `viewMode` prop with the following description in the README
>The default view to display when the picker is shown ('years', 'months', 'days', 'time').

Did you not find it or do you think this description is not clear enough? If it's unclear then I guess we have to update it :)

**Comment by mieryn** [comment]
Yes, changing viewMode changes what viewMode is shown first but only by leaving out days or months from the dateFormat you do not have to pick day or month at all (the month picker and/or day picker does not show up after selecting year/month). This was exactly the thing I needed and was glad to find out it exists :)

**Comment by simeg** [comment]
Ah, yes you are correct. Indeed it seems weird to leave this out of the documentation, I'll update it. Thanks for the input!
