### ISSUE TITLE
Timepicker stops registering clicks on mobile device

### ISSUE THREAD

**Issue by jonsvez** [YouCanBookMe/react-datetime#259]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Open the timepicker with a mobile device, hold down  one of the arrows so that the time-digits starts to change quickly. Then after a while, stop. Then try to change the digits of the one you did NOT hold down on. Nothing happens. Not also that I was using dateFormat={false}.

### Expected Results

see above

### Actual Results

see above

### Minimal Reproduction of the Problem

see above

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
I don't know how to get console output from a mobile device..

**Comment by simeg** [comment]
Hi @jonsvez. Thanks for the bug report.

To my knowledge this component has never officially supported any mobile browser. It's awesome if it does work, but I won't spend any time trying to fix bugs like these. I'm guessing there are other Datepicker components that do support mobile browsers that I'd recommend you to use. Sorry.

**Comment by jonsvez** [comment]
Yeah it works really nicely when the "input" is set to false (mobile devices tend to bring up their keyboard when an input is clicked, which covers the actual component ..). Other than holding down on the arrow-buttons it seems to work really good. 

> I'm guessing there are other Datepicker components that do support mobile browsers

Not really ^^ most of them suck

Anyway, keep up the good work

**Comment by simeg** [comment]
>Not really ^^ most of them suck

Too bad.. I just assumed some people were building mobile-friendly components. I don't have much experience building generic modules for mobile, but if you do I'd be happy to review a PR from you about this fix :) Or anything really.
