### ISSUE TITLE
Calendar always visible and not closing when clicking outside the element

### ISSUE THREAD

**Issue by nancruz** [YouCanBookMe/react-datetime#269]
The react datetime appears as opened by default. Even when I click outside the element they do not close. It started happening after upgrading to the latest version (2.4.5).

![image](https://cloud.githubusercontent.com/assets/1250918/22825754/e5136476-ef86-11e6-894c-f36b57d2bac9.png)

**Comment by simeg** [comment]
Hi @nancruz.

Exactly what props are you using?

**Comment by simeg** [comment]
@nancruz I just published version 2.8.6 which hopefully will resolve your problem. Let me know if it did not.

**Comment by nancruz** [comment]
@simeg sorry for the late response. I'm only using the "defaultValue" and "onChange" props.

I'll try again with the 2.8.6 version that you've just published and I will let you know.

**Comment by nancruz** [comment]
@simeg I've tried the version 2.8.6 and everything seems to work fine. Thanks!
