### ISSUE TITLE
"Blank" lines with no days related to the current month displayed on certain months

### ISSUE THREAD

**Issue by goodnightcat** [YouCanBookMe/react-datetime#279]
### I'm Submitting a ...

```
[x] Bug report
[] Feature request
[] Support request
```

In DaysView, sometimes there is a full line of days belonging to the past month, which shouldn't be displayed at all since the whole week belongs to the previous month and not the current month and the "empty week" simply doesn't anyhow relate. Same applies for a full line of days belonging to the next month, which sometimes appear on Februarys ending with last day of week.

I see in the code you're using hard-coded constant 42 to build the calendar table (I get it is 4x7 weeks for minimal length of the month + 2x7 for the first and the last line) but I'd expect you to drop the "blank" lines completely. You should be checking whether the previous month ended with the last day of week (to drop the first line) or current month ended with the last day of week (drop the last line).

### Steps to Reproduce
1. Open the example page
2. Set date to October 2000 - the first line only contains days from previous month - nothing related to current month
3. Set date to February 1999 - the last line only contains days from previous month - nothing related to current month
4. Set date to February 1998 - both the first are not related

### Expected Results
The lines containing no days related to current month should be dropped. Of course I get you'll lose the "fixed grid" of 7x6 to 7x5 or even 7x4 but the real question here is whether having it fixed is a necessary feature. Checking other date pickers on the market (mainly via flight companies' sites) not showing unrelated lines of days is an expected behaviour.

**Comment by simeg** [comment]
Hi @goodnightcat. I see what you mean and sure, maybe this is sub-optimal. However I don't feel like it is something that I want to spend my time on fixing. If you want to submit a PR then I'll gladly review it.
