### ISSUE TITLE
Add a way to set the viewDate dynamically

### ISSUE THREAD

**Issue by cyrilepinat** [YouCanBookMe/react-datetime#280]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

### Steps to Reproduce

Hi everybody, 
I would like to open datepicker at a date I dynamically specified.

Let me explain :
- I'm in viewMode "days"
- No date is selected
- I don't want to use defaultValue as it set the input value if initial value is undefined
- I use isValidDate to set a min date in my datepicker
- I change the minDate to 2 months later

### Expected Results
 
I want my datepicker opens at the first valid date so 2 months later (without any date selected yet)

### Actual Results

Cannot do it right ?

Thanks for your help

**Comment by jtadmor** [comment]
Right now I am doing this very, very dirty react code:

```
componentDidMount() {
    if (!this.props.value || this.props.defaultValue) {
      const viewDate = this.refs.dt.state.viewDate
      viewDate.hour(17)
      this.refs.dt.setState({ viewDate })
    }
  }
```

If we could just pass in a defaultViewDate that would be excellent :).

Happy to work on a PR.

**Comment by simeg** [comment]
Hi @cyrilepinat.

This is not possible right now, if you want you could try to come up with an approach to fix this. Otherwise I'd recommend you to use a parent component.
