### ISSUE TITLE
Versions 2.8.7 - 2.8.8 can break some builds

### ISSUE THREAD

**Issue by awkaiser** [YouCanBookMe/react-datetime#281]
### I'm Submitting a ...

```
[X] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

This issue _probably_ won't be noticed by most people, because I'm doing something a bit unconventional regarding Webpack `externals` transforms for React and React DOM, so consider this a "canary in the coal mine" report.

### Expected Results

No build error (like with `react-datetime` 2.8.6)

### Actual Results

```
Error: Cannot find module 'react-dom' from '/path/to/webpack/built/file'
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 

The 2.8.7 release caused problems thanks to [module dependency code introduced to `react-onclickoutside` in 5.x+](https://github.com/Pomax/react-onclickoutside/blob/b6c3be0da4d2207f2d7d171612343d216e902e90/index.js#L282-L295). I think this was a significant enough change to justify at least a minor version bump to `react-datetime`, if not a major. Instead, it went out as a patch version update, causing significant difference between `react-datetime` 2.8.6 and 2.8.7.

Glancing at other issues, it appears that `react-onclickoutside` upgrade (and related code changes) has introduced some other bugs as well? 😦 

**For now, I'm just version locking to 2.8.6**

**Comment by layneanderson** [comment]
Is this still a problem in 2.10.3?

**Comment by awkaiser** [comment]
My build process has changed since I filed this issue, and I'm no longer version locked on 2.8.6.

Since nobody else chimed in on this issue, I'd say it's safe to close.
