### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hours' of undefined

### ISSUE THREAD

**Issue by ferpintado** [YouCanBookMe/react-datetime#284]
```
Uncaught TypeError: Cannot read property 'hours' of undefined
    at Object.updateSelectedDate (http://localhost:3000/static/js/bundle.js:86604:8)
    at Object.updateSelectedDate (http://localhost:3000/static/js/bundle.js:86925:15)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:16912:17)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:16694:22)
    at Object.executeDispatchesInOrder (http://localhost:3000/static/js/bundle.js:16717:6)
    at executeDispatchesAndRelease (http://localhost:3000/static/js/bundle.js:16105:23)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/bundle.js:16116:11)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3000/static/js/bundle.js:17015:10)
    at Object.processEventQueue (http://localhost:3000/static/js/bundle.js:16319:8)
updateSelectedDate @ DateTime.js:319
updateSelectedDate @ DaysView.js:115
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:70
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147


```

I found this error that happens once in a while while changing the day. It even happens when clicking in the same day. 

I am using version 2.8.8

**Comment by simeg** [comment]
Hi @ferpintado. Can you provide a demo ([you can fork this](http://codepen.io/simeg/pen/mEmQmP)) or a step-by-step guide to recreating this bug? Otherwise it's very hard to find it.

**Comment by milasevicius** [comment]
Happens to me when I use render day prop. `renderDay={(props, currentDate, selectedDate) => (<td {...props}><span>{currentDate.date()}</span></td>)}`

**Comment by larrydahooster** [comment]
I need to revive this issue cause I am getting the same error once in a while in my sentry logs "Uncaught TypeError: Cannot read property 'hours' of undefined" with the same stacktrace that @ferpintado posted.

It happens constantly once in a while on different browsers and Operating Systems. But I was never able to reproduce it locally.  I don't use a custom render so the fix @milasevicius does not work for me.

As I cannot reproduce it locally, I only can make an assumption based on the breadcrumbs I get from sentry:

![screen shot 2018-01-15 at 15 53 45](https://user-images.githubusercontent.com/4989851/34948057-5b2f7bdc-fa0c-11e7-8758-4e218ed9b348.png)

As you can see the error happens right after a click on 
" tbody > tr > td.rdtDay.rdtActive > font > font"

So I assume that target of the event is not the td but the font. I think the target does not meet any of these checks https://github.com/YouCanBookMe/react-datetime/blob/v2.11.0/DateTime.js#L308 cause they expect the target to be the td with corresponding classes. 

If no criteria is met, date is undefined in this case: https://github.com/YouCanBookMe/react-datetime/blob/v2.11.0/DateTime.js#L328

**Comment by threecity** [comment]
Having the same issue with `renderDay` anytime I wrap the contents of the `<td/>` rather than just calling the date function:

WORKS:
```
return (
      <td
        {...props}
      >
        {currentDate.date()}
      </td>
    )
```

DOESN'T WORK:
```
return (
      <td
        {...props}
      >
        <span>{currentDate.date()}</span>
      </td>
    )
```

**Comment by gtnx** [comment]
I have the same behaviour that @larrydahooster. Could we reopen this issue @simeg ?

**Comment by gtnx** [comment]
Hello, this happens on a regular basis on my application. Can we reopen this issue?

**Comment by arqex** [comment]
Hey new version 2.16 is out and it should tackle this kind of errors. Thanks @ferpintado @milasevicius  and @larrydahooster for your date, it made possible the fix.

**Comment by Andrew-9** [comment]
static formatDuration(durationObj) {
    const duration = `${durationObj.hours ? (`${durationObj.hours}:`) : ''}${
      durationObj.minutes ? durationObj.minutes : '00'
    }:${
      (durationObj.seconds < 10)
        ? ('0' + durationObj.seconds)
        : (durationObj.seconds
        ? durationObj.seconds
        : '00')
    }`;
    return duration;
  }
};

TypeError: Cannot read property 'hours' of undefined

what can I do?
