### ISSUE TITLE
Time pickers as sliders

### ISSUE THREAD

**Issue by loaibassam** [YouCanBookMe/react-datetime#288]
Can we have the time picker as a slider? Something like this: https://dribbble.com/shots/1439965-Due-Date-and-Time-Picker

**Comment by layneanderson** [comment]
Nice looking feature request, however, no other feedback has been given (in 5 months) so I'll take this as there is no huge desire.  PR welcome though.  Closing.

**Comment by loaibassam** [comment]
Shame :'( been waiting for it for a while.
