### ISSUE TITLE
The active month is always Dec whenever the picker is hidden and opened again

### ISSUE THREAD

**Issue by z3h** [YouCanBookMe/react-datetime#289]
In my local application, i find that the month picker is always Dec active after it's hidden and opened again.
I tried the official demo again after that, but the result is same.

**Comment by jordancardwell** [comment]
+1

**Comment by jordancardwell** [comment]
@z3h just FYI there is a fix PR opened to solve this

**Comment by gordonk** [comment]
+1

**Comment by simeg** [comment]
@z3h @jordancardwell @gordonk 

Fixed with #293 (thanks @jordancardwell!). Update to `2.8.9` to get this fix.
