### ISSUE TITLE
Next/previous click targets do not align to CSS hover region

### ISSUE THREAD

**Issue by bcronin** [YouCanBookMe/react-datetime#290]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Summary: the on-hover highlight and the click target for moving the date forward / backward are not the same, which leads to put of the control "looking" clickable even when clicking will have no effect.

Specifically, the click target is set to the "SPAN" element containing the "›" character. The CSS hover highlight is on the containing "TD" element. If you're customized the CSS DateTime component to make the component significantly larger, the forward/backward buttons can appear "broken" if the user clicks inside the TD but outside the SPAN (the hover highlight suggests the whole area is clickable).

1. Visit over-simplified example here: http://codepen.io/bcronin/pen/BWmKYj
2. Click in any part of the gray region below that's below or above the "›" (see image below)

![image](https://cloud.githubusercontent.com/assets/432893/24009704/05c316e6-0a33-11e7-8f8c-5a06d412e32c.png)

### Expected Results

The whole highlighted region should act as the click target and cause the date to change.

### Actual Results

The date only changes if the click occurs in the `span` containing the arrow.  It fails silently if clicking above or below the `span` but still within the highlighted `td`.

### Minimal Reproduction of the Problem

See the CodePen in steps above.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)

The onClick could  be moved from the `span` to the `td` element in Day/Month/YearView.js:

```
render: function() {
 			return DOM.div({ className: 'rdtMonths' }, [
 				DOM.table({ key: 'a' }, DOM.thead( {}, DOM.tr( {}, [
-					DOM.th({ key: 'prev', className: 'rdtPrev' }, DOM.span({ onClick: this.props.subtractTime( 1, 'years' )}, '‹' )),
+					DOM.th({ onClick: this.props.subtractTime( 1, 'years' ), key: 'prev', className: 'rdtPrev' }, DOM.span({}, '‹' )),
 					DOM.th({ key: 'year', className: 'rdtSwitch', onClick: this.props.showView( 'years' ), colSpan: 2, 'data-value': this.props.viewDate.year() }, this.props.viewDate.year() ),
-					DOM.th({ key: 'next', className: 'rdtNext' }, DOM.span({ onClick: this.props.addTime( 1, 'years' )}, '›' ))
+					DOM.th({ onClick: this.props.addTime( 1, 'years' ), key: 'next', className: 'rdtNext' }, DOM.span({}, '›' ))
 				]))),
 				DOM.table({ key: 'months' }, DOM.tbody({ key: 'b' }, this.renderMonths()))
 			]);
```

**Comment by simeg** [comment]
Hi @bcronin and thanks for this! I agree that what you're suggesting makes much more sense, that's why I applied your suggested changes (https://github.com/YouCanBookMe/react-datetime/commit/c82df854356a45b9b29bc28967d6512f4531dbf0). These changes will be part of the next release. Thanks!
