### ISSUE TITLE
Hope adding date-range-pick feature

### ISSUE THREAD

**Issue by BBigLee** [YouCanBookMe/react-datetime#291]
### I'm Submitting a ...

```
[ ] Bug report
[ X ] Feature request
[ ] Support request
```

### Expected Results

Hope

**Comment by simeg** [comment]
Hi @BBigLee. If you want us to spend our free time and energy implementing a feature for you, the least you can do is write a proper request for it. Be super specific in describing your needs. This will have to be done in a new issue.
