### ISSUE TITLE
Which files need to be hosted?

### ISSUE THREAD

**Issue by sufuf3** [YouCanBookMe/react-datetime#292]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
Hi @YouCanBookMe   , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs/). We are going to host this library.

What the files should need to be added in cdnjs?
(I guess the files under `dist/` and `css/` need to be added in cdnjs.)

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#10731

**Comment by simeg** [comment]
Hi @sufuf3. Thanks for offering to host this component on your CDN. We'll get back to you soon.

**Comment by sufuf3** [comment]
@simeg Thanks.
And There are some files is missing from npm in v0.1.0 and v0.4.1, and  I can't get them from GitHub.
Is there any way can get the v0.1.0 and v0.4.1?

If you have any suggestions, please let me know.

Thank you.

**Comment by layneanderson** [comment]
It doesn't look like v0.1.0 nor v0.4.1 were official releases, therefore closing this issue.  Thanks for hosting on cdnjs.

**Comment by sufuf3** [comment]
Got it.
Thank you for your response.
