### ISSUE TITLE
React Datetime gets hang in IE browser when double clicked on Month view

### ISSUE THREAD

**Issue by piu** [YouCanBookMe/react-datetime#294]
Hi,

When using react-datetime in IE browser and click on Month view gives a error in Console for Array.from not found and also Array.find not found. After this the date-time control becomes irresponsive to any action in date-time control and hangs in IE. 
Below code pen is demo link from official site and this reproduces issue in IE 11 browser : [http://codepen.io/arqex/pen/BNRNBw](url)   

In order to fix this issue, I added polyfill for the Array.from and Array.find method and it resolved the issue. Below is the link which works in IE  11 as well as chrome: 
[http://codepen.io/anon/pen/LWJPJV](url) 

Can you please fix this issue in react-datetime itself? so that I dont have to make changes in library locally in my application.

**Comment by layneanderson** [comment]
Using a babel-polyfill in webpack will solve this issue.  The solution proposed still throws an error in IE 11 and is too much code for a limited issue.  Closing.
