### ISSUE TITLE
Avoid render days from next and previous month

### ISSUE THREAD

**Issue by ferpintado** [YouCanBookMe/react-datetime#299]
When a month is rendered few days of the previous and next month are rendered as well.

Is there a way to avoid this? 

![calendar](https://cloud.githubusercontent.com/assets/1950781/24511801/592eeb34-1532-11e7-87d1-4a49c4bc240d.jpg)

(Red lined what I DONT want to be displayed)

**Comment by simeg** [comment]
Hi @ferpintado. No, there's no way to avoid this behavior at the moment. If you want to submit a PR I'll gladly review it. Thanks.
