### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### ISSUE THREAD

**Issue by kadishmal** [YouCanBookMe/react-datetime#305]
### I'm Submitting a ...

```
[x] Bug report
```

### Steps to Reproduce

1. Update React to `v15.5.3`.
2. Build the code.
3. The warning: warning.js?8a56:36 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

### Expected Results

No warning should be displayed.

Looks like the fix would be very simple as there are only couple places that use `PropTypes` here https://github.com/YouCanBookMe/react-datetime/search?q=PropTypes&type=Code&utf8=✓.

**Comment by ccorcos** [comment]
Also createClass warning

**Comment by aaronmcadam** [comment]
Here's an example of how `enzyme` migrated to React 15.5: https://github.com/airbnb/enzyme/pull/876

**Comment by aaronmcadam** [comment]
Looks like #307 addresses this

**Comment by simeg** [comment]
Thanks @kadishmal for reporting this. Closing it as #307 was merged.
