### ISSUE TITLE
Empty defaultValue

### ISSUE THREAD

**Issue by dmr** [YouCanBookMe/react-datetime#309]
Is is possible to set an empty defaultValue?

```
<Datetime
      defaultValue={null}
     {...}
/>
```

always uses today.
I didn't find anything in other issues or documentation about this yet.

**Comment by simeg** [comment]
@dmr Hey, do you want it to always use today? In that case you can input `new Date()` as `defaultValue`. Or am I misunderstanding you?

**Comment by arch7tect** [comment]
Same issue here.  I do not need any default value, just empty input field.

**Comment by rikkit** [comment]
I had a similar issue #316. 

I just want an empty input field as well.

**Comment by layneanderson** [comment]
Sorry, I have to ask... If you have a null defaultValue what date would you want the calendar to open to when you click on it?  Some random arbitrary date many years in the past?

**Comment by rikkit** [comment]
I would expect it to open on the current month, but with no day selected.

**Comment by layneanderson** [comment]
That's kind of the _gotcha_ .  The defaultValue tells the component what date is should be on when it's first clicked.

**Comment by rikkit** [comment]
Setting value=null and not configuring defaultValue gives me the desired behaviour - calendar opens on the current month, with no day selected. When you click on a day, that day is selected. With this setup however it's not possible to initialise the picker with a date time.

I'm not convinced you've found a gotcha at all.... the default value for the purpose of rendering the component is not the same as the default value for the purpose of picking a date time.

**Comment by machoph** [comment]
just to clarify what @layneanderson says just just need to do something like this 
```
<Datetime
     isValidDate={this.validDate}
     defaultValue={appointment.scheduledOn ? moment(appointment.scheduledOn) : ""}
 />
```

**Comment by dmr** [comment]
I think it was a problem with moment() like you described, sorry for the bad feature request description.

Can I close this?
