### ISSUE TITLE
props locale doest not update

### ISSUE THREAD

**Issue by eversadia** [YouCanBookMe/react-datetime#31]
ex. <Datetime locale={this.props.locale} />

it seems that it only works on first load, it the props changes the  calendar locale render does not changed

**Comment by TheSharpieOne** [comment]
It will only update the props if the value changes

see: https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L150

**Comment by simeg** [comment]
This is a copy of #126. Closing this, please continue any discussions there.
