### ISSUE TITLE
Cannot change time constraints

### ISSUE THREAD

**Issue by skindc** [YouCanBookMe/react-datetime#310]
Hi.

It seems that changes to timeContraints property are not consumed by the TimeView after initial mount.
If this is intentional I will accept yet my scenario does require that the timeContraints may vary depending on which day is selected.

**Comment by simeg** [comment]
Hi @skindc. This is intentional though not wanted behavior. We're planning on fixing this and other props in version 3. If you feel like you can't wait you are welcome to publish a PR. Thanks.

**Comment by EmirGluhbegovic** [comment]
Hey, what is the state of the v3 release, or of any update? What is a recommended workaround?
