### ISSUE TITLE
viewMode='years' not working on IE11

### ISSUE THREAD

**Issue by kevinmuller1220** [YouCanBookMe/react-datetime#314]
###I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
I tried this with Internet Explorer 11.
On the demo page, http://codepen.io/simeg/pen/mEmQmP

I replaced ```<Datetime />,``` with ```<Datetime viewMode='years' />,```
And it showed me blank screen.

Any ideas?

**Comment by layneanderson** [comment]
I can confirm this bug (via codepen).  viewMode="months" also does not work in IE11.

**Comment by gor181** [comment]
It does not work as `Array.from` is not supported in **any** version of IE.

![image](https://cloud.githubusercontent.com/assets/8964589/26549186/073d6b32-4478-11e7-8b45-24fad7302be8.png)

So we can presume that this datepicker was built with Chrome, Firefox and Safari in mind..

**Comment by gor181** [comment]
Good thing is that if you use babel-polyfill you shouldn't have ie issues.

**Comment by layneanderson** [comment]
Recommend closing as babel-polyfill does solve the issue.
