### ISSUE TITLE
Error thrown when setting defaultValue to null

### ISSUE THREAD

**Issue by rikkit** [YouCanBookMe/react-datetime#316]
### I'm Submitting a ...

```
[ x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Set the defaultValue property to null.

### Expected Results
Same as setting value to null; input field is empty and picker doesn't have anything selected.

### Actual Results
Error thrown on line in DateTime.js getStateFromProps ```else if ( date.isValid && !date.isValid() )```: ```TypeError: Cannot read property 'isValid' of null```

### Minimal Reproduction of the Problem
JSX:

```
<DateTime defaultValue={null}/>
```

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)

Version ```"react-datetime": "^2.8.9"```

Tested in latest public Chrome and latest dev Firefox.

Current workaround is to just use ```new Date()``` as the defaultValue, but I prefer to not fill in values the user hasn't defined. I am using defaultValue instead of value so I can let the user freely type in the input, and show validation state without losing their input (using value and setState means that the user input is lost when setState causes a rerender).

**Comment by layneanderson** [comment]
Null is not valid for defaultValue, but it can be set to an empty string.  i.e. `defaultValue = ""`
