### ISSUE TITLE
Some files seem to miss in react-datetime@0.1.0 and 0.4.1

### ISSUE THREAD

**Issue by sufuf3** [YouCanBookMe/react-datetime#317]
Hi @arqex , 
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We are going to host this library.
But there are some files is missing from npm in `v0.1.0` and `v0.4.1`, and I can't get them from GitHub repo too.

So, where can I find the files in `v0.1.0` and `v0.4.1`?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#11082

**Comment by layneanderson** [comment]
The referenced cdnjs PR has been merged so I assume this can be closed.

**Comment by sufuf3** [comment]
Thank you. :)
