### ISSUE TITLE
Reopening calendar after click on input requires refocus

### ISSUE THREAD

**Issue by pstadermann** [YouCanBookMe/react-datetime#322]
### I'm Submitting a ...

```
[*] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

* Tab to input (calendar opens)
* Click on input
* Try to reopen the calendar

### Expected Results

* Clicking on the input reopens the calendar

### Actual Results

* You can only reopen the calendar if you refocus the input (click somewhere else, click on input). This is hard to understand for the user.

**Comment by sonakshichomal-kiwi** [comment]
+1

**Comment by ottenkoop** [comment]
+1

**Comment by Miskamyasa** [comment]
+1

**Comment by fernandops26** [comment]
+1, this request is important.

**Comment by simeg** [comment]
Hey everyone. I just saw this issue and the PR and the code looks good. Because the original PR had conflicts I put the code into my own PR (#460). I'm closing this issue, for further questions or comments put them in the PR. Thanks.
