### ISSUE TITLE
closeOnSelect not working properly

### ISSUE THREAD

**Issue by bradeac** [YouCanBookMe/react-datetime#324]
Hello,

After going through some of the other bug entries related to this, I still couldn't find a solution.

I am using react-datetime with **Redux Forms**. The code looks something like this, nothing fancy:

                <DateTime 
                    closeOnSelect={true}
                    dateFormat="YYYY-MM-DD"
                    timeFormat={false}
                />

When I click on it, nothing happens. If I minimize my browser window after clicking and then I restore the window, the calendar is opened and when I click on a date, it closes, as expected.

I am using the latest version of react-datetime, redux forms and also the latest version of react.

Also, probably important, if I don't use closeOnSelect, the component works as expected.

Thank you.

**Comment by comatory** [comment]
I'm having the same problem. I pass value to picker from state, so nothing unusual. My fix was to do something like:
```
<DateTime
  onChange={this.onChange.bind(this)}
  ref='calendar'
  ...
/>
```

I do not pass `closeOnSelect` prop to `DateTime`, instead I handle closing the calendar manually in my `onChange` callback using `closeCalendar` method:

```
onChange(proxy) {
   // do something here
  this.refs.calendar.closeCalendar()
}
```

**Comment by jimmyn** [comment]
Any updates here? I have the same problem

**Comment by LuciRebecca** [comment]
Is it related to this section, starting at 156:

```
if ( this.props.closeOnSelect && this.state.currentView !== 'time' ) {
				// updatedState.open = false;
                updatedState.open = nextProps.open;
			} else {
				updatedState.open = nextProps.open;
			}
```
I removed the if statements to leave just 
```
updatedState.open = nextProps.open;
```

And it's now working as expected. I'm calling with:

```
<Datetime inputProps={disabled} className={classes}  closeOnSelect={true} open={this.state.calendarOpen} timeFormat={false}  dateFormat='DD-MM-YYYY'/>
```

**Comment by ipinak** [comment]
Same issue here.

**Comment by simeg** [comment]
I'm not sure what to do here. You are asking for help where this component is used with another wrapping component. If someone could setup a project with this integration + showing the problem it would make debugging it a whole lot easier. We do not explicitly support redux-form but if you search this repo there are other people having problems with redux-form, and some solutions. Here's a few examples: #287, #148 & #377.

**Comment by simeg** [comment]
I believe some related issues has been fixed in later versions, it might be worth to try with a later version. Closing for now.
