### ISSUE TITLE
Typescript Definition for DatetimeickerProps.value is incorrect according to property comment

### ISSUE THREAD

**Issue by narthollis** [YouCanBookMe/react-datetime#336]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

`DatetimeickerProps.value` is defined as accepting a JavaScript `Date` object, however the comment of this property suggests that anything that moment can parse is accepted.

This means the typing for `DatetimeickerProps.value` should be `Date | string | moment.Moment`

Currently to avoid typing issues we need to either case value as `any` thereby throwing out any type checking, or construct a JS `Date` representation (which causes the component to not work if the user has not yet entered a complete data by keyboard), 

(This looks also to be the case for `defaultValue`

**Comment by simeg** [comment]
Hi @narthollis. Nice catch, I've adjusted this in #461. Closing this issue, continue any discussion in the PR. Thanks!
