### ISSUE TITLE
how to trigger the calendar with button

### ISSUE THREAD

**Issue by vxba** [YouCanBookMe/react-datetime#337]
I'm Submitting a ...

[] Bug report
[ ] Feature request
[x] Support request

I want to open the calendar with a button when click. How to do that?
thank!

**Comment by Keith-Ball** [comment]
Seems like something that could be solved with the following:

```
// In the component
toggleCalendar() {
  this.setState({ calendarOpen: !this.state.calendarOpen });
}

render() {
  return (<div>
    <Button onClick={toggleCalendar} />
    <Datetime open={this.state.calendarOpen} />
  </div>
}
```

Note that this is psudo-code, but it should work all the same.

**Comment by vxba** [comment]
Thank @Keith-Ball I'll try.

**Comment by gitdevzwt** [comment]
@Keith-Ball You are right i have click in button time picker is open but blur event not triggering in click outside of box.
