### ISSUE TITLE
Disable manually typing in date/time

### ISSUE THREAD

**Issue by tylerzika** [YouCanBookMe/react-datetime#339]
[ ] Bug report
[x] Feature request
[x] Support request

I'd like it to be: when the user inputs the date/time, they can only make changes by using the pop out calendar/clock. Allowing them to type it in manually is prone to errors.

**Comment by rikkit** [comment]
isn't this what the ```input``` option is for? just set it to false.

**Comment by tylerzika** [comment]
@rikkit, that's is not what `input` currently does. When I set it to `false`, it completely hides the input field.

Setting `input` to `false`.

<img width="504" alt="screen shot 2017-05-27 at 3 26 09 pm" src="https://cloud.githubusercontent.com/assets/1011888/26524712/2fbfe216-42f1-11e7-91c1-4449abdae0b7.png">

Setting `input` to `true`.

<img width="415" alt="screen shot 2017-05-27 at 3 27 24 pm" src="https://cloud.githubusercontent.com/assets/1011888/26524726/7f185cb2-42f1-11e7-8006-285d00c03f1e.png">

**Comment by rikkit** [comment]
> Whether to show an input field to edit the date manually.

I guess I interpreted it wrong, I thought the option referred to the text input field i.e. html ```input``` element. Would CSS work for you? 

```css
.rdt input {
  display: none;
}
```

**Comment by AtomicAlienZ** [comment]
@tylerzika wouldn't `readOnly` input prop solve your problem or am I missing some use case?

**Comment by jpmoyn** [comment]
@AtomicAlienZ you can just put the `readOnly` prop in like so?

`<Datetime readyOnly />`

Because that isn't working for me. I'm not sure what I am missing.

**Comment by jpmoyn** [comment]
Nevermind, I found the solution. @tylerzika check [this issue](https://github.com/YouCanBookMe/react-datetime/issues/46) and see if it helps.

**Comment by tylerzika** [comment]
@jpmoyn this is what my component looks like

```js
<ReactDateTime
   onChange={sendDateTime => this.updateSurveySentRecord({target: {name: "SEO__Survey_Sent__c", value: sendDateTime}})}
   className="slds-datepicker"
   closeOnSelect={true}
   value={this.state.sendDateTime}
   readOnly={true}
 />
```
and look what I can still do...

![screen shot 2017-06-15 at 4 36 55 pm](https://user-images.githubusercontent.com/1011888/27205955-e766e076-51e8-11e7-9500-77e4b89ec286.png)
![screen shot 2017-06-15 at 4 37 02 pm](https://user-images.githubusercontent.com/1011888/27205959-ebe8aeea-51e8-11e7-8499-68aff7b926ad.png)
😕

**Comment by jpmoyn** [comment]
@tylerzika if you followed the link i sent you should have seen that the syntax for the specific input props is ```inputProps={{readOnly: true}}```, not just `readOnly={true}`.

**Comment by tylerzika** [comment]
@jpmoyn thanks, sorry I didn't look at it right, I thought `inputProps` was a variable... Works perfectly!

**Comment by mouradmamassi** [comment]
you can use attribut `onkeydown="return false" `

**Comment by otelom** [comment]
@mouradmamassi I can't make it work, can you show me some code?

**Comment by mouradmamassi** [comment]
@otelom  Yes off course this is my code 
//HTML
<input type="text" id="datefin_search"  onkeydown="return false">
//JS
  var mycalanderfin = new dhtmlXCalendarObject(["datefin_search"]);

**Comment by mouradmamassi** [comment]
@otelom Are you using **datepicker** for **reactJS** ?

**Comment by otelom** [comment]
@mouradmamassi, I'm using react-datetime for ReactJS


Com os melhores cumprimentos,
Otelo Magalhães

2018-02-14 15:23 GMT+00:00 Mourad MAMASSI <notifications@github.com>:

**Comment by mouradmamassi** [comment]
@otelom  I hope this method can do the job for you ;)
https://codepen.io/anon/pen/jZGEXX?editors=1111

**Comment by otelom** [comment]
@mouradmamassi Thanks, that did the job. But I'm using ES6 so it was a little bit different but after I adapted it worked. Thanks again ;)

**Comment by mouradmamassi** [comment]
@otelom  you're welcome

**Comment by adish1997** [comment]
If you want to want it to remain clickable/editable but just disable input via keyboard you can try
React:
<input type="date" onKeyDown={(e) => e.preventDefault()} .... />

HTML:
<input type="date" onkeydown="return false" />

**Comment by gauravmahor-zwt** [comment]
<DateTime inputProps={{readOnly:true}} />

**Comment by gauravmahor-zwt** [comment]
<DateTime inputProps={{readOnly:true}} />

**Comment by gauravmahor-zwt** [comment]
<DateTime inputProps={{readOnly:true}} />

It might help
