### ISSUE TITLE
Reduce the timepicker window size

### ISSUE THREAD

**Issue by David-OConnor** [YouCanBookMe/react-datetime#340]
How can I reduce the size of a time-picker window? It's currently 3 times the size it needs to be, cause excess mouse movements. I'm referring to the popup, not the input field.

**Comment by simeg** [comment]
This could be achieved using CSS, there's no javascript to help you with this. I think it would be rather cumbersome to do this though, since the component is built for looking exactly like it does. Good luck and be sure to report back here how it went :)
