### ISSUE TITLE
Bug counter when increasing

### ISSUE THREAD

**Issue by 7gonchaar7** [YouCanBookMe/react-datetime#341]
Hi, guys!
I need to set min value for hours ( timeConstraints={{ hours: { min: 8 } }} ). When I open a counter I see default value - 00:00 (there must be 08:00 I think). I see 01:00, 02:00, 03:00 ... instead of 09:00, 10:00 ... when increase counter. Please solve this situation

**Comment by simeg** [comment]
If I understand you correctly, this might be what you're looking for
```js
timeConstraints={{hours: {min: 8, step: 1, max: 12}}}
```

It seems you also have to provide a `max` but the `step` is optional.

Closing this now since it was months since it was opened, let me know if you want to re-open it.
