### ISSUE TITLE
How do I set the timezone of the date picker when it need to be empty on first load?  

### ISSUE THREAD

**Issue by holyman2k** [YouCanBookMe/react-datetime#342]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[ x] Support request
```

How do I set the timezone of the date picker when it need to be empty on first load?  

I know I can set the timezone by create a moment object with timezone, but if the date picker must be empty at the start how do I set the timezone?

ps, set the timezone after user selection does not work since the moment object after selection is in the browsers timezone.

**Comment by simeg** [comment]
Hi @holyman2k.

Right now the timezone prop is stupid, it does not listen for updates. We have this in our roadmap for the next major version.
