### ISSUE TITLE
Help with import statement

### ISSUE THREAD

**Issue by simonh1000** [YouCanBookMe/react-datetime#346]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[X ] Support request
```
I'm try to use your package with the following code. A while ago I got the datetime pikcer to render but I made some changes have never since been able to get past the error below, despite trying various approaches (see comments). This is the code I currently have (regrettably I did not commit at the moment it did work). Any advice?
```
import React from 'react';
import ReactDOM from 'react-dom';

// require('react-datetime');
// var Datetime = require('react-datetime');
// import * as Datetime from 'react-datetime'
import Datetime from 'react-datetime'

function datepicker(d, cb) {
    requestAnimationFrame( () => {
        console.log("datapicker")
        ReactDOM.render(
            <Datetime />,
            document.getElementById('reactDate')
        );
        console.log("datapicker2")
    });
}

export default datepicker;
```

> index.js:2978 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

**webpack 2 - webpack.config.js**
```
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ["env", 'react']
                    }
                }
            }, {
```

**Comment by gs-luke** [comment]
`import * as Datetime from 'react-datetime';`
works for me

**Comment by rikkit** [comment]
I use the same as @gs-luke 

From what I understand, if you have ``` exclude: /node_modules/,``` in your Webpack you have to ensure all libraries are loaded by the page before your Webpack bundle. Is this happening?

**Comment by simeg** [comment]
Hi @simonh1000. I'm sorry but I don't know what might be causing problems at your end. What you could do is look into the [react-datetime-playground](https://github.com/arqex/react-datetime-playground) repo to see the configuration there. Maybe it will help you in some way (ping @rikkit).

**Comment by simonh1000** [comment]
Yes, thanks @gs-luke that seems to have fixed it. I honestly don't how it went from working to not-working and back to working again....

**Comment by invious** [comment]
I did `import * as Datetime from 'react-datetime';`

and get the same error :(

![image](https://user-images.githubusercontent.com/1996089/42100426-22a4d812-7b8e-11e8-80a1-dfbc3b5b2468.png)

**Comment by invious** [comment]
If I do:
```
require('react-datetime')
```

sorry new to React... can't figure out how to get this to work

![image](https://user-images.githubusercontent.com/1996089/42100570-8efdd3e2-7b8e-11e8-8874-25b055753b1f.png)

**Comment by invious** [comment]
if I do
```
const Datetime = require('react-datetime')
```

I get the same error I do for `import * as Datetime from 'react-datetime';`

**Comment by itsmichaelwang** [comment]
This sounds dumb, but I was tearing my hair out trying to figure out why it wasn't working. Make sure you've installed moment: `yarn install moment`.

It says to do it in the documentation but I didn't read closely enough. :)
