### ISSUE TITLE
Add class to selected day on calendar.

### ISSUE THREAD

**Issue by padsbanger** [YouCanBookMe/react-datetime#358]
```
[ ] Bug report
[x] Feature request
[ ] Support request
```

Hello, I can see that class `rdtToday` is added to correct day, but is it possible to add class to selected day on the calendar, so it is possible style it diffrently ?

**Comment by simeg** [comment]
Hi @padsbanger.

No, that specific feature is not available. But you can always use your own style to override any styling coming from this component, which I think should be enough.
