### ISSUE TITLE
Can't use two equal names of week day

### ISSUE THREAD

**Issue by naomifeehan** [YouCanBookMe/react-datetime#36]
Hi, there is issue if I use equal week day names:

weekDayNames={["S", "M", "T", "W", "T", "F", "S"]}

Warning: flattenChildren(...): Encountered two children with the same key, `.$T`. Child keys must be unique; when two children share a key, only the first child will be used.
warning.js:48 Warning: flattenChildren(...): Encountered two children with the same key, `.$S`. Child keys must be unique; when two children share a key, only the first child will be used.
warning.js:48 Warning: flattenChildren(...): Encountered two children with the same key, `.$T`. Child keys must be unique; when two children share a key, only the first child will be used.
warning.js:48 Warning: flattenChildren(...): Encountered two children with the same key, `.$S`. Child keys must be unique; when two children share a key, only the first child will be used.

**Comment by arqex** [comment]
Thanks for the feedback, I'll have a look at it.

**Comment by naomifeehanmoran** [comment]
Cheers, see PR #37

**Comment by ralphholzmann** [comment]
Sorry for tacking onto an old issue, but is this functionality still available? I don't see `weekDayNames` documented anywhere, and I am looking for the same functionality in the current version. Is there a new/different method to achieve the same effect?
