### ISSUE TITLE
react-datetime + open and disableOnClickOutside prop don't work together

### ISSUE THREAD

**Issue by ravishah990** [YouCanBookMe/react-datetime#363]
I have problem for closing date picker  here my code

`<Datetime
open
disableOnClickOutside={false}
timeConstraints={timeobj}
isValidDate={valid}
defaultValue={`today date`}
dateFormat="MMM DD [at]"
inputProps={obj}
closeOnSelect
/>
`

Using, this code date picker  open by default when I select then date picker would be close. but my problem is when I click outside then date picker not close so how should I close this date picker when I click outside.

**Comment by simeg** [comment]
I think this issue has been fixed in later versions. Please try a later version.
