### ISSUE TITLE
Add id to input 

### ISSUE THREAD

**Issue by shogan94** [YouCanBookMe/react-datetime#365]
Sorry if this is a dumb question or has already been answered, but I haven't seen it anywhere. 

But is there a way to add an `id` to the `input` that gets rendered? 
My controller looks like....
`                <Datetime
                    id={input.name}
                    value={dispdate}
                    inputProps={inputProps}
                    timeFormat={false}
                    closeOnSelect={true}
                    onChange={(value) => input.onChange(value)}
                    onBlur={input.onBlur}
                    isValidDate={isValidDate}
                    {...custom}
                />`

But the id doesn't get passed along. 
`<div class="rdt"><input type="text" class="form-control" value="" placeholder="Graduation year"><div class="rdtPicker"><div class="rdtYears"><table><thead><tr><th class="rdtPrev"><span>‹</span></th><th class="rdtSwitch" colspan="2">2010-2019</th><th class="rdtNext"><span>›</span></th></tr></thead></table><table><tbody><tr><td data-value="2009" class="rdtYear">2009</td><td data-value="2010" class="rdtYear">2010</td><td data-value="2011" class="rdtYear">2011</td><td data-value="2012" class="rdtYear">2012</td></tr><tr><td data-value="2013" class="rdtYear">2013</td><td data-value="2014" class="rdtYear">2014</td><td data-value="2015" class="rdtYear">2015</td><td data-value="2016" class="rdtYear">2016</td></tr><tr><td data-value="2017" class="rdtYear">2017</td><td data-value="2018" class="rdtYear">2018</td><td data-value="2019" class="rdtYear">2019</td><td data-value="2020" class="rdtYear">2020</td></tr></tbody></table></div></div></div>`

I'd like it to be `<input id="whatever input.name was" type="text" value="" placeholder="Graduation year"> 

Main reason for doing this is to make it more accessible. Currently not having the `id` is giving me quite a bit of accessibility failures.

**Comment by jeremyhamilton** [comment]
@shogan94 I was experiencing the same issue, if you pass the option as inputProps then that should solve your problem.

`<Datetime inputProps={{ id: 'yourInputID', name: 'yourInputName'}} ... />`

**Comment by shogan94** [comment]
Ah thank you! That did the trick
