### ISSUE TITLE
Only display month and day, not year

### ISSUE THREAD

**Issue by tsnolan23** [YouCanBookMe/react-datetime#373]
I see that there is way to only show things like month and year using
```
dateFormat="YYYY-MM"
```
However, it doesn't seem to work with just Month and Day, I want to be able to omit the year:
```
dateFormat="MM-DD"
```

**Comment by simeg** [comment]
Hi @tsnolan23.

[In this demo](https://codepen.io/simeg/pen/XaXdRG) it's working for me. Maybe you have some other props active which is causing this problem?

**Comment by tsnolan23** [comment]
@simeg, correct, the display of the selected date works correctly, but we wanted to remove the year from the date picker all together. We realized that this is not really a normal request from our design team, so we built a custom one. Thanks for the response, but we can close this!
