### ISSUE TITLE
Calendar doesn't open on focus when closeOnSelect=true

### ISSUE THREAD

**Issue by tonoslav** [YouCanBookMe/react-datetime#377]
I am using **latest version** of **react-datetime** with **redux-form**
Everything works fine but when I set **closeOnSelect=false**

Calendar **doesn't open** (popup) when I first click into input for date
It works only when I click into , click outside and than again click inside that input.

**Component use example**
> <Datetime 
>                 {...input}
>                 defaultValue={value}
>                 inputProps={{
>                     className: className
>                 }}
>                 dateFormat={format}
>                 timeFormat={false}
>                 closeOnSelect
>                 locale="sk"
> />

**Comment by copycut** [comment]
Same issue with version 2.9.0.

**Comment by tonoslav** [comment]
The problem is in **DateTime.js -> function componentWillReceiveProps**

![image](https://user-images.githubusercontent.com/3399021/30642437-417c8444-9e0b-11e7-9c01-abdae43556d0.png)

**componentWillReceiveProps** is called on **input focus** so **updatedState = {}** than
updatedState.open === undefined
closeOnSelect = true
currentView != time
so it closes which is not good , I don't even understand that condition with view != time 
But I think this is the place where it need some fix

Actual props 
![image](https://user-images.githubusercontent.com/3399021/30642730-4e610bca-9e0c-11e7-8c9e-074b26ce4cf5.png)


I couldn't fix it by myself 

Used packages

![image](https://user-images.githubusercontent.com/3399021/30642792-857bacbe-9e0c-11e7-9e3d-dffb72c0b6bd.png)

**Comment by tonoslav** [comment]
It actually opens but right after it closes

**Comment by tonoslav** [comment]
**FIXED**

Finally I managed to do it somehow, not sure what helped but my few changes are

![image](https://user-images.githubusercontent.com/3399021/30643439-2aa84772-9e0f-11e7-92de-42119a6f94d2.png)

I am using redux form and I assigned all props from input they create I think it wasn't right
1. So I removed {...input} ( => this.props.input)
2. Added only **value** and **onChange** (this.props.input.(value/onChange)
3. Set **open** to **false**
