### ISSUE TITLE
Not compatible with React v16

### ISSUE THREAD

**Issue by vouill** [YouCanBookMe/react-datetime#380]
I'm Submitting a ...

[X] Bug report
[ ] Feature request
[ ] Support request

Since react 16 removed `.DOM` from the react package, the component cannot be used with the latest beta release of react.

See this [comment](https://github.com/facebook/react/issues/10294#issuecomment-318210497) 

I tried this [PR#358](https://github.com/YouCanBookMe/react-datetime/pull/353) And it worked very fine. What is preventing you for merging it ? I can help if needed :)

Thanks for the awesome work anyway !

**Comment by layneanderson** [comment]
I'll be coming on board as a maintainer shortly.  This is likely the 1st PR I'll merge.  We are just currently waiting for the owner of the repository to come back from vacation to grant me rights.

**Comment by vouill** [comment]
Awesome, thanks for the input!

**Comment by simeg** [comment]
@vouill Thanks for posting this issue, and as you can see the PR has been merged and deployed!
