### ISSUE TITLE
npm install react@2.18.11 fails with missing dependency: @types/react

### ISSUE THREAD

**Issue by wired-walker** [YouCanBookMe/react-datetime#382]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

npm install react-datetime

### Expected Results

react-datetime installs successfully

### Actual Results

npm ERR! code E404
npm ERR! 404 no such package available : types/react
npm ERR! 404
npm ERR! 404  'types/react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-datetime'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
Rolling back to 2.18.10 fixes this problem.

**Comment by brandtabbott** [comment]
Same problem here.

**Comment by shadowwzw** [comment]
I also have this problem

**Comment by Unsfer** [comment]
Same for me

**Comment by simeg** [comment]
That is weird, the following works for me.

```sh
$ mkdir react-datetime-test
$ cd react-datetime-test
$ npm install react-datetime
npm WARN saveError ENOENT: no such file or directory, open '/react-datetime-test/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/react-datetime-test/package.json'
npm WARN react-datetime@2.8.11 requires a peer of moment@>=2.16.0 but none was installed.
npm WARN react-datetime@2.8.11 requires a peer of react@>=0.13 but none was installed.
npm WARN react-datetime@2.8.11 requires a peer of react-dom@>=0.13 but none was installed.
npm WARN react-datetime-test No description
npm WARN react-datetime-test No repository field.
npm WARN react-datetime-test No README data
npm WARN react-datetime-test No license field.

+ react-datetime@2.8.11
added 22 packages in 2.437s
```

But you are telling me it's not working for you?

**Comment by wired-walker** [comment]
Our private npm repo (using sinopia) seems to be causing this issue. Switching to the public registry (https://registry.npmjs.org/) works, so closing this.

**Comment by simeg** [comment]
@brandtabbott @shadowwzw @Unsfer Is @wired-walker 's solution ^ helping you as well?

**Comment by shadowwzw** [comment]
We also have a private npm repo (sinopia). It seems that the problem is with us.

**Comment by brandtabbott** [comment]
Ahh, yes, this happening on a private sinopia server as well for me.  Thanks!
