### ISSUE TITLE
Time Format

### ISSUE THREAD

**Issue by chriscamplejohn** [YouCanBookMe/react-datetime#393]
### I'm Submitting a ...
```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Other Information
How do you disable the AM/PM on the time selector? I am using timeFormat="HH:mm" which correctly formats the time using the 24 hour format. However the time selector still shows the AM/PM selector. How do I disable it?

Thanks
Chris

**Comment by JABirchall** [comment]
From what I can see, you can not change it through props.
Maybe put up a feature request or bug report for the select to follow the dateFormat and timeFormat provided?

**Comment by layneanderson** [comment]
Hi @chriscamplejohn ,

Setting timeFormat like you have should work (I use this a lot in my web apps).  What do you have in your dateFormat?

**Comment by chriscamplejohn** [comment]
I have dateFormat={false} as I am using separate date and time pickers.

**Comment by layneanderson** [comment]
Can you show more code?  I can't easily reproduce this problem.  Have a look at this [CodePen](https://codepen.io/layneanderson/pen/ayyOJg), it works as expected.

**Comment by chriscamplejohn** [comment]
Sorry for the delay - only just back looking at this. It is weird as the laptop I was working on is showing the problem I described but having got the same source out on another machine it is working fine and the AM/PM is hidden.

Thanks for your help.
