### ISSUE TITLE
DateConstraint

### ISSUE THREAD

**Issue by JABirchall** [YouCanBookMe/react-datetime#398]
### I'm Submitting a ...
```
[ ] Bug report
[x] Feature request
[ ] Support request
```

This has a timeConstraint prop, how ever today we decided we need need to constrain the Date to not be less then current date, Can this be added! We have a check ATM in the onChanged but since this has a Time Constraint already it would make sense to have a Date Constraint

**Comment by layneanderson** [comment]
Hi @JABirchall ,

This is already a feature, please see [Selectable Dates](https://github.com/YouCanBookMe/react-datetime#selectable-dates).

If this solves your issue please close.

Cheers

**Comment by JABirchall** [comment]
Ahh thank you, that achieved what I was looking for.
