### ISSUE TITLE
`create-react-class` required but not listed in package.json

### ISSUE THREAD

**Issue by vjpr** [YouCanBookMe/react-datetime#399]
https://github.com/YouCanBookMe/react-datetime/blob/cf3d9288c97e65fdc66500b5bdc18604f97f0b85/src/CalendarContainer.js#L4
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Try install with `pnpm`.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 

```
ERROR in ./~/.registry.npmjs.org/react-datetime/2.9.0/~/react-datetime/src/YearsView.js
Module not found: Error: Can't resolve 'create-react-class' in '/xxx/node_modules/.registry.npmjs.org/react-datetime/2.9.0/node_modules/react-datetime/src'
 @ ./~/.registry.npmjs.org/react-datetime/2.9.0/~/react-datetime/src/YearsView.js 4:18-47
 @ ./~/.registry.npmjs.org/react-datetime/2.9.0/~/react-datetime/src/CalendarContainer.js
 @ ./~/.registry.npmjs.org/react-datetime/2.9.0/~/react-datetime/DateTime.js
```

**Workaround**

Install `create-react-class` top-level.

**Comment by simeg** [comment]
Hi @vjpr. This dependency was accidentally removed by a previous PR. Thanks for reporting, I fixed it with https://github.com/YouCanBookMe/react-datetime/pull/400. We'll release a new version soon.
