### ISSUE TITLE
Setting "open" property doesn't seems to do anything.

### ISSUE THREAD

**Issue by dennis90** [YouCanBookMe/react-datetime#406]
### I'm Submitting a ...
```
[X] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Create a component with a datetime component.
2. Define internal state to this component with the values: `{openCalendar: false}`
3. Define to datetime component props `input={false}` and `open={this.state.openCalendar}`
4. Try to change `openCalendar` state value to `true`
5. Nothing will happen.

### Expected Results
According to documentation, I would expect calendar component to be displayed after changing `openCalendar` value

### Actual Results
The property "open" doesn't reflect on component's internal state.

### Minimal Reproduction of the Problem
https://codepen.io/dennis90/pen/xLzLRM

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
Changing "open" property does not reflect on component's internal state, the value of property should be applyed to internal state "open" property.

**Comment by thsmrtone1** [comment]
Can confirm. Seems to only apply to initial state. If component gets rendered with a hard `open={true}` seems to work.

**Comment by enepomnyaschih** [comment]
FWIW here's a workaround I could find:

1. Set initial state to `{showDatePicker: false, datePickerHack: 0}`
2. Render date picker as `{this.state.showDatePicker && <ReactDatePicker key={state.datePickerHack} .../>}`
3. Every time I change `showDatePicker` I also increment `datePickerHack`

Looking forward for a normal fix.

**Comment by simeg** [comment]
Hi. Thanks for the elaborate bug report! We are aware that this property is broken, and we have it on our roadmap to fix it. See [the backlog](https://github.com/YouCanBookMe/react-datetime/projects/1).

**Comment by SachaG** [comment]
Fixed via https://github.com/YouCanBookMe/react-datetime/pull/476
