### ISSUE TITLE
Customizing the time picker

### ISSUE THREAD

**Issue by rchanou** [YouCanBookMe/react-datetime#41]
I see how to do formatting in the input field, but is there any way to customize the time picker? I want it to only go from 1-12 for the hour picker and add an AM/PM toggle button.

**Comment by 0xF013** [comment]
+1

**Comment by rchanou** [comment]
react-bootstrap-datetimepicker has the opposite problem (only AM/PM, no 24-hour timepicker), though it looks like they're working on releasing a fix: https://github.com/quri/react-bootstrap-datetimepicker/issues/105

**Comment by 0xF013** [comment]
if only that thing had seconds picker

**Comment by arqex** [comment]
We probably will be able to add this feature defining a `timeFormat` prop with an `a` or `A`

http://momentjs.com/docs/#/displaying/

so making `<DateTime timeFormat={hh:mm A} />` would switch to the AM/PM mode.

**Comment by crobinson42** [comment]
+1 
I'd like to see this feature as well. I'm glad to help with this enhancement with contribution guidelines.

**Comment by bandanaman** [comment]
Switching to AM/PM mode would be great feature, but since widget and date format are two separate things, maybe better idea is to specify time type with an attribute: `< DateTime twelveHourClock={ false } />`

**Comment by andrewmclagan** [comment]
plus one, would be a great feature

**Comment by bandanaman** [comment]
I added this functionality in my fork https://github.com/bandanaman/react-datetime and created pull request. It works as arqex described in his post - searches for " A" in entered time format.

**Comment by andrewmclagan** [comment]
Will take a look. Thanks!

**Comment by ecerroni** [comment]
+1 
I'd like to see this feature as well.

**Comment by andrewmclagan** [comment]
Any chance this PR will be merged?

**Comment by simeg** [comment]
Closing this as referenced PR is merged.

**Comment by rchanou** [comment]
Awesome, will the latest version be pushed to npm soon?
