### ISSUE TITLE
Broken date

### ISSUE THREAD

**Issue by Unsfer** [YouCanBookMe/react-datetime#412]
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
open https://codepen.io/anon/pen/wqQZgN
focus on input

### Expected Results
Normal calendar

### Actual Results
Days in current month are all gray, and 2nd of May just don't wanna be a Saturday

### Screenshot
![bug](https://user-images.githubusercontent.com/13516005/29870443-8a395b4a-8d98-11e7-84fd-f45980bec5e2.png)

**Comment by Unsfer** [comment]
And if you click to the left arrow you will be moved to the March, skipping April

**Comment by layneanderson** [comment]
When I click on the codepen it seems to be working fine.
![image](https://user-images.githubusercontent.com/21086971/30242419-f1b2ad8a-954a-11e7-8724-7b676a824f04.png)

**Comment by Unsfer** [comment]
Seems like it's because of browser compatibility.
I'm trying on Chrome 35 and Firefox 45.9.0 and it's broken.
On the latest version of Chrome works fine too.

**Comment by layneanderson** [comment]
I've found most browser compatibility issues (typically IE) can be fixed using babel-polyfill in your build.  Is that an option for you?

**Comment by Unsfer** [comment]
But i'm already using it.
Just noticed a warning:
```
Warning: flattenChildren(...): Encountered two children with the same key, `3_31`. Child keys must be unique; when two children share a key, only the first child will be used.
    in tr (created by Unknown)
    in tbody (created by Unknown)
    in table (created by Unknown)
    in div (created by Unknown)
    in Unknown (created by OnClickOutside(Component))
    in OnClickOutside(Component) (created by Unknown)
```

**Comment by layneanderson** [comment]
Going to assume this is due to the unique key issue.  The codepen doesn't seem to have any issues.  Closing.
