### ISSUE TITLE
`while` statement seems to cause an infinite loop

### ISSUE THREAD

**Issue by motoakim** [YouCanBookMe/react-datetime#416]
### I'm Submitting a ...

```
 [x] Bug report
 [ ] Feature request
 [ ] Support request
```

### Steps to Reproduce

When I try to do like this the problem happened

      <DateTimePicker
            onChange={newDate => this.updateFromDate(newDate)}
            format={"x"}
            isValidDate={(currentDate, selectedDate) => {
              const yesterday = moment().subtract( 1, 'day' );
              return currentDate.isAfter(yesterday) && this.isAvailable(currentDate);
            }}
            timeFormat={false}
            value={this.state.from}
      />

### Expected Results

Just show "from" and "to" forms 
### Actual Results

It doesn't stop loading without any error code on terminal or devtool
### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
I got this bug when I worked on https://github.com/sachaG/zensroom this project. 
And After I try to debug the bug,  this line's `while` seems to be suspicious.
https://github.com/YouCanBookMe/react-datetime/blob/8f6f3312403adbc3260c031e65d0c594e86a7e93/dist/react-datetime.js#L259

Sorry if there are any mistakes / misunderstandings. Thanks

**Comment by Bazze** [comment]
I'm having the same issue with the latest version. I reverted back to `2.9.0` which solved the issue. We probably need to revisit the https://github.com/YouCanBookMe/react-datetime/commit/9509fac6de4707178d9744f2591a1f82790447cd commit in order to fix this bug.

**Comment by layneanderson** [comment]
It's at the top of my to-do list.  Unfortunately I'm a little tied up with other things at the moment.

**Comment by eferte** [comment]
same problem, version 2.9.0 solved the issue for me too.

**Comment by therealedsheenan** [comment]
how about remove `node_modules` and reinstall the dependencies?

**Comment by layneanderson** [comment]
Should be fixed on 2.10.3.
