### ISSUE TITLE
Date picked should be displayed when picker is re-opened after a Submit

### ISSUE THREAD

**Issue by cdwebdev** [YouCanBookMe/react-datetime#417]
[ ] Bug report

### Steps to Reproduce

1) Hook this date picker up such that it can send info to the server
2) Select a date and time
3) Submit this date and time via your form
4) After successful submission, date is displayed in input field
5) Open the date picker

### Expected Results
Date Time Picker should now show the date that was initially selected

### Actual Results
Date Time Picker seems to show todays date.

Question:
How can this be set? Perhaps Default Value can be used somehow

**Comment by layneanderson** [comment]
You can use `value` to set this, but your form will have to return it after submission.

I don't believe this is a bug but rather a support question.

**Comment by cdwebdev** [comment]
Yes I agree, This is not a bug, but it was relying on the way the data was being sent back from the backend.
