### ISSUE TITLE
The command `npm run test:all` fails after cloning the repo

### ISSUE THREAD

**Issue by tansongyang** [YouCanBookMe/react-datetime#418]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Clone the repo.
2. Install dependencies.
3. Do `npm run test:all`.

### Expected Results

Tests should pass.

### Actual Results

Tests do not pass.

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
The failing tests are snapshots. I am trying to do a pull request to update TypeScript types, and this issue is preventing me from committing. Since my changes are unrelated to snapshots, I could commit without the hook, but doesn't seem like the right thing to do.

**Comment by layneanderson** [comment]
I'm actually getting the same thing.  It's making me a little gun-shy to merge anything until I resolve this.

I can update the snapshots and get all the tests to pass, but then the CI tests break when I push the branch.

**Comment by tansongyang** [comment]
@layneanderson Are you one of the core maintainers? Or do you know of one of them that we can contact?

**Comment by layneanderson** [comment]
I'm the newest maintainer.  It's really just simeg and me right now though.

**Comment by tansongyang** [comment]
OK. Thanks for taking a look. My changes aren't critical, so it's no problem for me if it takes some time for this issue to get resolved.

**Comment by layneanderson** [comment]
I've had a chance to look into this briefly.  If I change my timezone to Stockholm, then all the tests pass.  Next up researching Jest and Travis a bit more.  @simeg feel free to jump in if you have any insights.

**Comment by simeg** [comment]
Some tests that uses time and dates uses dynamic values, which is pretty bad. I just fixed one test that was failing and set a static date.

Regarding snapshots, they are there for you to make sure that the changes you do are reflected properly in the rendered HTML. So if you do a change that you know will affect the HTML, just run `npm run test:snapshot:update` and commit the changes.

Feel free to re-open this if the problem persist.

**Comment by johnhunter** [comment]
New to this repo. I forked in order to merge PR https://github.com/YouCanBookMe/react-datetime/pull/573.

Had the same issue with tests. The fix was to update the npm scripts to force the timezone:
```json
"test": "TZ=Europe/Stockholm ./node_modules/.bin/jest",
...
"test:snapshot": "TZ=Europe/Stockholm ./node_modules/.bin/jest snapshot",
"test:snapshot:update": "TZ=Europe/Stockholm ./node_modules/.bin/jest snapshot --updateSnapshot",
```

**Comment by rafaelpcustodio** [comment]
Hello, guys. I'm using this lib in my project and when I run the tests in one day, it runs and passes normally, but if I wait 1 or 2 dayy, if I run it again it fails due to dynamic changes on some Date that changes the snapshot. How can I avoid this behavior? Is there a way to avoid being necessary to update the snapshots every time I run the tests in a different day?
