### ISSUE TITLE
How to get value from mulitiple date inputs?

### ISSUE THREAD

**Issue by aaronucsd** [YouCanBookMe/react-datetime#43]
If i have many on the same page, how do i get the value of each one? Is there a way to specified an id for each or?

**Comment by ZombiEquinox** [comment]
I realize this is an old post, but I am running into the same issue. Did you figure out how to do it? I am having issues pulling the date value from one component to another.

**Comment by aaronucsd** [comment]
Yes. Like so

  //handle click event from datepicker
  onDateChange = (key) => (newDate) => {
    if (newDate !== 'Invalid date') {
      this.setState({
        [key]: newDate / 1000,
      });
    }
  };

**Comment by scheung38** [comment]
I am very trying to find out: 

I have added 

export default class MomentInputDemo extends TrackerReact(React.Component) {
     constructor() {
        super()
        this.state = {time: ''}
        this.handleChange = this.handleChange.bind(this);
    }

    handleChange(newDate) {
        if (newDate !== 'Invalid date') {
            this.setState({
                [key]: newDate / 1000,
            });
        }
     }

    render() {
        return '',
            <DateTime
            onChange={this.handleChange}
            />
    }

But key is not defined?

**Comment by simeg** [comment]
@scheung38 that doesn't sound like the problem lies with react-datetime. It sounds like your webpack config is off. [I searched for your error](https://www.google.com/#q=Missing+class+properties+transform) and got some hits which I think may help you.

Closing this as the original author resolved his issue. Thanks people.
