### ISSUE TITLE
Any chance I can use the date picker portion only?

### ISSUE THREAD

**Issue by SnitramDev** [YouCanBookMe/react-datetime#436]
Any chance I can use the date picker portion only?

**Comment by rikkit** [comment]
The docs say this -

> timeFormat | boolean or string | true | Defines the format for the time. It accepts any Moment.js time format (not in localized format). If true the time will be displayed using the defaults for the current locale. If false the timepicker is disabled and the component can be used as datepicker, see available units docs.
