### ISSUE TITLE
Month select feature request

### ISSUE THREAD

**Issue by fonty422** [YouCanBookMe/react-datetime#438]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[x] Support request
```
### Version
Using version 2.8.6

### Issue
I'm currently using this as intended in several parts of my application, and it functions just fine, but I have an additional need to use just the calendar-picker part without the input field.

1. Can I trigger it to open by clicking a generic object (like a div, button, or icon) rather than the input field? I can't seem to set the `open` state to `true` on a prop change and also have `closeOnSelect` set to `true`. It's either open all the time, or closed all the time.

2. I can't seem to modify the props of the input field to match a custom css. Is there an example on how to modify this - in particular colours,backgrounds, borders, font type/size etc. This would negate the need for 1.

3. I would also like to select a month only - I don't need a full date. Clicking a month should simply return the first of the selected month. Does this exist already? Or do I need to create my own function for `onViewModeChange` to handle this?

**Comment by bjbrewster** [comment]
Hello

You *should* be able to manage the opening and closing yourself by setting prop `open` to true or false and input to false to hide the input.  I think others have reported this feature as broken though.  There is an active feature request to allow passing a custom renderInput method that will render the input box so you could render whatever you like.

Your third issue is already implemented.  Simply pass a dateFormat string that contains only Year and Month format tokens (eg `MMMM, YYYY` or similar) and you will get onChange notifications on month select.  Same for a year selector, just pass `YYYY`.  See http://momentjs.com/docs/#/parsing/string-format/ for all format tokens.

Cheers,
Brendan

**Comment by simeg** [comment]
1) This is not possible today, unfortunately. We have it on the roadmap for v3 though.
2) You can use the `inputProps` prop to apply any attributes to the input HTML element. If you want to change the CSS you can just include CSS that points to the input (`.rdt > input.form-control` for example).
3) As Mr @bjbrewster points out you can use `viewMode={'months'}` for this.
