### ISSUE TITLE
Moment.js v2.19 breaks build

### ISSUE THREAD

**Issue by lopis** [YouCanBookMe/react-datetime#445]
### I'm Submitting a ...
[x] Bug report
[ ] Feature request
[ ] Support request

### Steps to Reproduce

* Clone fresh new react-datetime
* Install dependencies with `npm install`
* Run `npm run dev`

### Expected Results
One should see a success message ending with `webpack: Compiled successfully.`

### Actual Results
```
WARNING in ./~/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/home/joao/code/react-datetime/node_modules/moment/src/lib/locale'
 @ ./~/moment/src/lib/locale/locales.js 65:16-60
 @ ./~/moment/src/lib/locale/locale.js
 @ ./~/moment/src/moment.js
 @ ./DateTime.js
 @ ./example/example.js
 @ multi webpack/hot/dev-server webpack-dev-server/client?http://localhost:8080 ./example/example.js
```

Seems like the latest version of moment throws this error. The `package.json` allows this version to be used. For the time being, this dependency should be capped to version 2.18.1 (https://github.com/moment/moment/releases).

**Comment by bjbrewster** [comment]
This is why we can't have nice things

https://github.com/moment/moment/issues/4216

**Comment by lopis** [comment]
Can confirm their patch works for us.
