### ISSUE TITLE
Using the input to change AM/PM does not update the time input view

### ISSUE THREAD

**Issue by mattbasta** [YouCanBookMe/react-datetime#446]
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
1. Open the time view
2. Change the AM/PM portion of the timestamp in the textbox

### Expected Results
The the toggle for AM/PM should update appropriately

### Actual Results
The toggle does not update

**Comment by layneanderson** [comment]
Hi @mattbasta ,

I can't duplicate this problem.  It seems to work fine on our [demo](https://youcanbookme.github.io/react-datetime/) page.

Also looking into you code fix #446 it looks like you are trying to do this on "H" format which is a twenty-four hour format (am/pm doesn't apply).

**Comment by mattbasta** [comment]
I can confirm that this issue does in fact exist on your demo page. See the gif below.

This does operate on `'H'`. The 24-hour hour value is what is kept in state and is used to calculate whether AM or PM is displayed. The bug that's resolved in this PR is that the value of AM/PM is based on the previous hour value (currently in `this.state`) rather than the new hour value (that's being calculated in `calculateState()`).


![react-datetime](https://user-images.githubusercontent.com/279498/31959112-ad460724-b8a8-11e7-8660-14b8b794dd76.gif)

**Comment by layneanderson** [comment]
Interesting.  I think there might be more going on here.  To start if `timeFormat` is false it shouldn't show a time (a bug in the demo).  Switching the `timeFormat` to `hh:mm A` and doing changing just the "A" or "P" I can reproduce like the gif above.  However if I change the entire "AM" or "PM" portion it works as expected.

**Comment by mattbasta** [comment]
@layneanderson Changing the full two characters is two updates. On the second update, `this.state` has the correct value for hour, so it correctly computes the value. Changing the "a" to a "p" and updating any other character (with the obvious exception of the hour in certain cases) will also cause it to update to the correct timestamp.
