### ISSUE TITLE
Customise input field

### ISSUE THREAD

**Issue by timothyarmes** [YouCanBookMe/react-datetime#45]
Hi,

It would be great if we could add children to the input element. That would allow us to add icons. For example, using Semantic UI I'd like to produce output like this:

```html
<div class="ui left icon input">
  <i class="calendar icon"></i>
  <input type="text" placeholder="Enter tags">
</div>
```

I tried this:

```jsx
<div className='ui left icon input'>
   <i className='calendar icon' />
   <DateTime
      timeFormat={false}
      isValidDate={this.validFromToday}
      inputProps={{ placeholder: T('datePlaceholder')}}
      onChange={(value) => this.handleChange('startDate', value)} />
</div>
```

But that doesn't work since you're wrapping the input.

**Comment by arqex** [comment]
This is a hard request. I can't open the markup of the component to be editable completely. But maybe you can update your css to place the icon in the right position. Replacing the input clas by a datepicker one:
```
<div className='ui left icon datepicker'>
   <i className='calendar icon' />
   <DateTime
      timeFormat={false}
      isValidDate={this.validFromToday}
      inputProps={{ placeholder: T('datePlaceholder')}}
      onChange={(value) => this.handleChange('startDate', value)} />
</div>
```

Maybe you can position the `i` element absolutely over the datepicker input.

**Comment by timothyarmes** [comment]
That would be really awkward.

How about if you could however accept a 'prefix' and 'postfix' property that would insert components either side of the input....

**Comment by aseem2625** [comment]
Is there anyway I can pass a prop which acts placeholder for the input?

**Comment by timothyarmes** [comment]
inputProps={{ placeholder: 'blah')}}

**Comment by aseem2625** [comment]
@timothyarmes  Thanks :) Worked.

**Comment by ConAntonakos** [comment]
Any advice as to how to customize the input `name` property? I tried `inputProps={{name: 'blah}}` but to no avail. Looking at the source.

**Comment by hiepndd** [comment]
Hi @arqex!
In `react-datetime`. How can I allow user only input number and slash symbol when they can manual input date instead of select from calendar.
Sorry for any inconvenience.
Thanks in advance.

**Comment by ron766** [comment]
> inputProps={{ placeholder: 'blah')}}

this is not working for me
