### ISSUE TITLE
Hours stuck on pressing up/down hours arrows

### ISSUE THREAD

**Issue by lukeaus** [YouCanBookMe/react-datetime#450]
### I'm Submitting a ...

```
[X] Bug report
[ ] Feature request
[ ] Support request
```
### Steps to Reproduce
Go to [demo page](http://codepen.io/simeg/pen/mEmQmP)
Select time, then press on up/down links for hours til hours get stuck.

### Chrome 61 on macOS
e.g. stuck at 3am
![react-datetime-stuck-hours-3am-4am](https://user-images.githubusercontent.com/5635204/31975924-10b7f2d6-b980-11e7-8138-78a4f6b02b3c.gif)

### Safari 11 on macOS
e.g. stuck at 1am
![react-datetime-stuck-numbers-1am-2am](https://user-images.githubusercontent.com/5635204/31975898-f396d302-b97f-11e7-9bae-b1dfceb8c001.gif)

### Expected Results
Hours should increase/decrease with clicking on hours buttons.

### Actual Results
Hours gets stuck increase/decrease with clicking on hours buttons.

**Comment by simeg** [comment]
This is weird. I just tried this on my Mac with Chrome 61 and Safari 11 and it works. I tried clearing my cache in Chrome before it as well.

@lukeaus could you try clearing your cache? Idk what else could be wrong.

**Comment by lukeaus** [comment]
Thanks for getting back to me @simeg. 

Yeah it's weird. I just tried on both browsers using the steps to reproduce and now it works.

I haven't looked at the code but there must be something going on as it happened in 2 different browsers.

**Comment by simeg** [comment]
Yeah, that it's happening in two browsers speaks for something else being wrong, you're correct.

Anyway, closing this for now since it's working for you.

**Comment by lukeaus** [comment]
OK. Let's see if anyone else runs into this one.
