### ISSUE TITLE
Behaviour on mobile Safari

### ISSUE THREAD

**Issue by mlajtos** [YouCanBookMe/react-datetime#456]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Use react-datetime on iOS Safari.
2. Scroll page to show the whole component.
3. (Datetime closes. Input field has still focus.)
4. Tap input field. (It does nothing.) Tap it multiple times.
5. Tap somewhere else, then back on the input field.
6. Select the date.

### Expected Results

Steps 3., 4., 5. should not be necessary.

### Actual Results

Madness, anger, frustration.

### Minimal Reproduction of the Problem

See "Steps to Reproduce".

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
None.

**Comment by simeg** [comment]
Hi @mlajtos and thanks for publishing a bug report! We currently have no explicit support for any browser on the phone, sorry. I'm hope this doesn't adds to your frustration.

**Comment by mlajtos** [comment]
Hi Simon,
I will fix it myself during the next week. (Easy fix; event handling is a bit mixed up.)
Should I submit a PR with a fix afterwards?

**Comment by simeg** [comment]
@mlajtos Great to hear :) Yes, please! That would be awesome.
