### ISSUE TITLE
Open calendar to specific date (without *setting* the date)

### ISSUE THREAD

**Issue by SachaG** [YouCanBookMe/react-datetime#468]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

Here's my use case: I have two datepickers where people can pick the start and finish dates for a trip. If we're currently in November and people select "June 2nd" as the start date for their trip, I would like the second datepicker to automatically open in June, and not in November like it does by default. 

Is there a way to achieve this without having to actually set the `value` prop for the second datepicker?

**Comment by SachaG** [comment]
Oh perfect! I can finally get that item off my to-do list :)

**Comment by simeg** [comment]
@SachaG I'll do it right away :)

**Comment by simeg** [comment]
Fix available in `v2.13.0`.

**Comment by SachaG** [comment]
Trying to get it to work inside Codepen, not quite there yet… Btw the `/dist` files still say `2.12.0`. I don't know if the files are wrong, or if it's just the version number?

https://github.com/YouCanBookMe/react-datetime/blob/94dde5590a472f9a671578ffd4607cd53a94b322/dist/react-datetime.js#L2

**Comment by SachaG** [comment]
So `viewDate` works when I set it to a static date value, but not when I try to dynamically set it via `state`: 

https://codesandbox.io/s/m3rwm69mlj

Is it only taken into account when the calendar first mounts, and not updated later on?

**Comment by SachaG** [comment]
OK, that's good to know. I'm happy to submit a PR if you can point me in the right direction (which file/PRs to look at?)

**Comment by simeg** [comment]
Looking through the PRs I found these:
- https://github.com/YouCanBookMe/react-datetime/pull/266
- https://github.com/YouCanBookMe/react-datetime/pull/206

Basically when the state updates you check if it's different from the next/previous state and if so, update accordingly.

In my head this should be done for all props by default, iterating over all of them. Not having one `if` statement for every prop, but that's in the future :) No need to do that now.

Let me know if you need anything else.
