### ISSUE TITLE
is it possible to customize rendering of `.rdtSwitch`?

### ISSUE THREAD

**Issue by iwinux** [YouCanBookMe/react-datetime#472]
https://github.com/YouCanBookMe/react-datetime/blob/39b8275f9b2bbd8f11ffecba94fce7d339c4d577/src/DaysView.js#L21

In some locale (e.g.: `zh-cn`), it should be rendered as `YYYY-MM` instead of `MMM YYYY`.

**Comment by simeg** [comment]
To answer the question in the header, no it's not possible to do that right now. However, you can affect the output of the value with the prop `dateFormat`.

**Comment by Hillshum** [comment]
Is this something that would be considered if a pull request was provided?
