### ISSUE TITLE
Need closeCalendar in renderInput function 

### ISSUE THREAD

**Issue by lzwsoar** [YouCanBookMe/react-datetime#477]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

Now we have openCalendar, why closeCalendar absent? It is necessary to customize the Input I think. For example, someone need close the calendar when ESC tapped.

**Comment by simeg** [comment]
Hi @lzwsoar.

Thanks for your suggestion. I just published a new version with this functionality implemented. It was a one-line-change so I just fixed it. It's in version 2.12.0.
