### ISSUE TITLE
Allow next and prev arrows render

### ISSUE THREAD

**Issue by MarciDavid** [YouCanBookMe/react-datetime#478]
Hi

You have a really good component here.
The implementation and adjustments were very easy and the documentation is very clear.

We want to change the style a bit, is there a change to allow renderArrow function?

Thanks a lot

**Comment by simeg** [comment]
Hi @MarciDavid.

There is no prop to change the arrows, however you can always override the CSS to make it look the way you want it to. Feel free to post a PR for it, it shouldn't be too complicated to write.
