### ISSUE TITLE
onChange return data

### ISSUE THREAD

**Issue by grayds** [YouCanBookMe/react-datetime#480]
At present, it appears that a Moment object is returned upon an onChange event.  Is there a way to return additional parameters, such as the component's id or name field?  I have several <Datetime /> components and would prefer not to generate a custom handler for each one.  The goal is to have a generic handler to update the state from any <Datetime /> component.

**Comment by thedailynathan** [comment]
@grayds  I saw you closed this, did you find a solution for your problem? In particular I'm trying to write a generic onChange handler, which usually receives an `event.target` from which I can extract both the value and name of the input. It doesn't seem possible to retrieve the name with the react-datetime.

**Comment by grayds** [comment]
I created a wrapper component to solve this problem. The wrapper is where I defined the name attribute.
