### ISSUE TITLE
Time is really difficult on the iPad

### ISSUE THREAD

**Issue by davidworkman9** [YouCanBookMe/react-datetime#487]
As of iOS 10, you can no longer turn off double tap to zoom, so tapping on the time buttons causes the page to zoom in instead of changing the time. Is there any way that tap and hold could do what click and hold does on the desktop and go spin through the numbers until you lift?

**Comment by simeg** [comment]
I agree, and we both want to merge your PR so I'm closing this as it will be fixed soon.

**Comment by emersonthis** [comment]
I'm still seeing this exact problem on my iPhone running iOS 14.3. It seems like PR #488 wasn't supposed to fix the annoying zoom problem, but was meant to enable click+hold scrolling through the numbers, and I can't do that either. It seems like a small thing, but it makes the time picker almost unusable on an iPhone. Should we reopen this?

https://user-images.githubusercontent.com/1728139/105643628-cf621c80-5e45-11eb-8282-91f152c39a9a.mp4
