### ISSUE TITLE
defaultValue is set but not selected

### ISSUE THREAD

**Issue by Vishal1419** [YouCanBookMe/react-datetime#489]
When I provide default value to react-datetime, it displays the defaultValue in textbox, that's good. But when I open the calendar, the value is not selected in calendar.

For example, if I provide 02-02-2018 as default value, then I can see 02-02-2018 00:00 in the textbox but nothing is selected in calendar.

**Comment by GSolari79** [comment]
Did you find what was wrong? I am facing the same isse

**Comment by vnktsh** [comment]
Hi, can you tell how did you solve this?

**Comment by Vishal1419** [comment]
@vnktsh Its been 2 years now. Sorry, I don't remember.

**Comment by vnktsh** [comment]
No probs. I found it; I have used 'viewDate' props. Thanks.
