### ISSUE TITLE
RangeDatePicker - Prev and next arrows issue

### ISSUE THREAD

**Issue by MarciDavid** [YouCanBookMe/react-datetime#490]
Hi

### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```
I working with your component for a while and it's really simple to understand and work with.
I'm trying to extend it to a rangeDatePicker (see attached).
![capture](https://user-images.githubusercontent.com/22189520/34380890-807125ca-eb0d-11e7-8498-7bda4b88e1db.PNG)

As you can see I have 2 calendars and just 2 arrows instead of 4 arrows.
Those 2 arrows needs to slide the 2 calendars together by month for each side.
What can I do to make this thing happens?

### Expected Results
Each arrow will slide both calendars

### Actual Results
Each arrow slide just the calendar it's belongs to.

Thanks a lot,
David

**Comment by simeg** [comment]
Hi @MarciDavid.

I'm not sure what you are asking for. We don't support multiple calendars so you must have done something on your own. We don't support date ranges either.

Could you specify exactly what you need help with?

**Comment by davidmarciano** [comment]
Not relevant anymore, thanks for your comment.
