### ISSUE TITLE
daysOfWeekDisabled prop is not working 

### ISSUE THREAD

**Issue by techyrajeev** [YouCanBookMe/react-datetime#491]
I tried to disable the days selection for certain days using `daysOfWeekDisabled` and passing an array for the days ( starting from sunday and so on ).

` <DateTimeField daysOfWeekDisabled={[0,1,2]} /> `

Is this feature not available yet or I am doing something wrong.

**Comment by simeg** [comment]
Hi @techyrajeev.

The prop `daysOfWeekDisabled` does not exist, I'm not sure where you got that from. See [the documentation](https://github.com/YouCanBookMe/react-datetime#selectable-dates) on how to limit the days.
