### ISSUE TITLE
For tagged and npm released v2.12.0 it appears react-datetime in dist/ is v2.11.0

### ISSUE THREAD

**Issue by rluiten** [YouCanBookMe/react-datetime#500]
### I'm Submitting a ...

```
[ x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Go to https://github.com/YouCanBookMe/react-datetime/blob/v2.12.0/dist/react-datetime.js
or https://github.com/YouCanBookMe/react-datetime/blob/v2.12.0/dist/react-datetime.min.js

Both show `react-datetime v2.11.0` in content.

An npm installed of v2.12 also shows disk/react-datetime.js as `react-datetime v2.11.0`

Examining componentWillReceiveProps() i can see it is not v2.12.0 by the looks of it.

Running `npm run build:win` in a local clone of the repo at v2.12.0 produces what appears to be the updated v2.12.0 in the dist folder.

**Comment by simeg** [comment]
Nice catch. However the dist files are not the files we export in our npm package. This has been a known bug for quite some time now and I'm not sure why someone hasn't just fixed it.

See https://github.com/YouCanBookMe/react-datetime/blob/master/package.json#L10

I remember trying to fix it but not sure why I just didn't. I'll get around to it eventually, but it's not a huge thing. Thanks for notifying us though!
