### ISSUE TITLE
timeconstraints work only once when component is loaded 

### ISSUE THREAD

**Issue by knnemade99** [YouCanBookMe/react-datetime#504]
timeConstraint property works only once when component is loaded, but if we change the timeConstraint props and send the new props to the React Datetime component, it does not reflect unless we re-render the React Datetime component. I think timeConstraint is handled in willMount of the React Datetime component, but its not handled in willReceiveProps method.

Any help will be appreciated.
Thanks

**Comment by simeg** [comment]
This is a known bug, that prop updates are not reflected in the component. It's on our roadmap for v3. For now I would recommend a different component or a parent component that causes react-datetime to be re-rendered.

**Comment by knnemade99** [comment]
but by controlling it with it's parent component all the state of the component resets, hence it don't behave properly, like open of calendar, view mode of calendar and so on.

**Comment by simeg** [comment]
Sorry, this component cannot do what you want it to do right now, in the future it will. I'd suggest you use a different datepicker component.

**Comment by knnemade99** [comment]
Okk thanks.
