### ISSUE TITLE
Mouse cursor is pointer when it shouldn't be (for time picker)

### ISSUE THREAD

**Issue by kaiyoma** [YouCanBookMe/react-datetime#505]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Go to the time picker and move the mouse off of a clickable element.

### Expected Results
The mouse cursor should change to the default.

### Actual Results
The mouse cursor stays as "pointer".

### Minimal Reproduction of the Problem
Any existing demo exhibits this behavior in any browser.

**Comment by simeg** [comment]
Nice catch, thanks! I'll make sure it's fixed in the next version.

**Comment by simeg** [comment]
Fixed in #511.

**Comment by simeg** [comment]
Fix available in `v2.13.0`.
