### ISSUE TITLE
calendar.openCalendar() doesn't seem to work

### ISSUE THREAD

**Issue by SachaG** [YouCanBookMe/react-datetime#510]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

I'm trying to manually trigger a calendar to open. I've added a `ref` to the component:

```
<DateTimePicker
  ref={(ref) => { this.toCalendar = ref; }}
/>
```

And I would then expect to be able to do `this.toCalendar.openCalendar()` to open the calendar; but that doesn't do anything. The weird part is that I can log out `this.toCalendar` to my console, and if I call `openCalendar()` from there it *does* work. 

This might very well be a problem with my code and not with the package, so if anybody has suggestions on what I could try to debug the issue that would be very helpful.

**Comment by simeg** [comment]
Sounds weird. You can pass `open: true` for it to open, I believe.

**Comment by SachaG** [comment]
Yes, but then I run into the other issue (https://github.com/YouCanBookMe/react-datetime/issues/509).

**Comment by simeg** [comment]
Ouch. Would you be able to provide a CodePen example of this behaviour? [This one](https://codepen.io/simeg/pen/mEmQmP) has the latest react-datetime code loaded.

**Comment by SachaG** [comment]
A minimal example works: https://codepen.io/SachaG/pen/qxRQbb

So it's probably something else in my code… I'll keep looking :)

**Comment by SachaG** [comment]
OK, I've narrowed it down: apparently `openCalendar()` stops working if you do a `setState` in the same function: https://codepen.io/SachaG/pen/zRZWZg?editors=0110

**Comment by simeg** [comment]
Wow, great work narrowing down the issue. Would you mind submitting a PR with a fix? (and maybe a test or two, if possible)

**Comment by SachaG** [comment]
I'm not very familiar with the code yet so until I have time to submit a proper PR I made one to add some documentation about `openCalendar`: #513

**Comment by SachaG** [comment]
Closing this because we decided using `ref` is an anti-pattern. If you do need to use it, here are some additional details (use at your own risk!):

---

# Manually Opening the Calendar

In some cases, you'll want to manually get the calendar to open. While you can do so by setting `open` to `true`, another approach is to call the calendar's `openCalendar` method. For that, you'll need to make the calendar available via its `ref` property: 

```js
class Calendar extends React.Component {
  constructor() {
    super();
  }

  render() {
    return (
      <div>
        <button onClick={this.datetime.openCalendar}>Open</button>
        <Datetime
          ref={ref => {
            this.datetime = ref;
          }}
        />
      </div>
    );
  }
}
```

Note that if you would like to modify the parent component's `state` at the same time, you'll need to call `openCalendar` in your `setState`'s callback: 

```js
this.setState({ foo: 'bar' }, this.datetime.openCalendar);
```

Here is a more complex example involving [two calendars](https://codesandbox.io/s/m3rwm69mlj).
