### ISSUE TITLE
API Breaking Changes (major version bumps)

### ISSUE THREAD

**Issue by simeg** [YouCanBookMe/react-datetime#519]
@arqex @layneanderson and anyone else that is interested.

This is a growing problem, I'm constantly "turning down" feature requests because I don't want to break the current API of the component. Doing a major bump for breaking the API is the semantic way to go, but I have this feeling that I want to collect as many breaking changes as possible before doing a major bump.  This results in me never doing any work with any features for v3 and just post-poning it.

Should we be OK with bumping a major version for every PR that breaks the API? This could potentially result in v10 in a few months.

What are your thoughts?

**Comment by rikkit** [comment]
It seems like projects typically gather all api breaking changes into a "next" branch and release it when it's ready, whilst only supporting the current major version for non-breaking changes. It's a little bit of management but not really anything complicated. Would that not work for react-datetime? It allows you to hold off releasing the new major version until it's featureful enough for you, whilst actually being able to make those changes. Right now, it seems like this project is in a state where version 3 will never exist.

My personal opinion is that the major/minor breaking change distinction is fairly meaningless in a practical sense - you have to do full testing of your integration with a library either way. So you can either be strict with semantic versioning and get to v10 in two months, or you can have reasonable version number increases. Realistically if you go with the "next version" branch option, you don't have to decide to bump the version until you want to release it.

**Comment by arqex** [comment]
From my point of view there is no problem on bumping versions everytime there is a breaking change, getting to the v10 in 2 months is not a problem because of the number of the version, but for the number of times we make the devs have a look at their react-datetime integration.

@rikkit's idea sounds great. We can have a next branch where the breaking changes can be batched, and release a new version when that branch seems stable with the new features.

We always wanted to do a big refactoring and maybe because of that we never do it, this strategy would allow to make deeper changes.

**Comment by simeg** [comment]
@rikkit What is the difference between a "API changes" and "API contract changes"? I meant changes that would break backward-compability.

@arqex Yes, that's what I meant, not having developers have to come here every other month.

The proposal you have makes sense.. maybe if you all of the time waiting for "that big re-write" it'll never happen.

**Comment by rikkit** [comment]
@simeg Sorry - just a language quirk. They mean the same thing. I've edited to make it clearer.

**Comment by layneanderson** [comment]
I would prefer the way that @rikkit suggests.  Like he said a lot of other projects do it this way.  This also allows for more experimentation.

I think another problem that we will have to be careful about is what features get added.  A lot of projects start with a simple straight forward API and over time features get added and the API becomes huge.  But I digress as this is really another topic.

**Comment by simeg** [comment]
@layneanderson I totally agree with the huge API problem. Looking at the API for this component it could certainly be improved. We have some props that was added for solving a specific problem (which there is nothing wrong with) but it would be nice to have fewer props that does more. Which is something we could strive for with a v3.
