### ISSUE TITLE
How to use the component with TypeScript

### ISSUE THREAD

**Issue by szabolcsx** [YouCanBookMe/react-datetime#526]
### I'm Submitting a ...

```
[x] Bug report?
[ ] Feature request
[x] Support request
```

Hi,

I'm trying to use `react-datetime` in my TypeScript project, but I get a runtime error if I try to import it like the way it's mentioned in the readme.

### Steps to Reproduce

Import `Datetime` in `typescript` and try to render the component.
### Expected Results

No runtime error

### Actual Results

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

### Minimal Reproduction of the Problem

``` TS
import * as React from "react";
import * as ReactDOM from "react-dom";
import * as Datetime from "react-datetime";

const Component = () => <Datetime />;

ReactDOM.render(
    <Component />,
    document.getElementById("app")
);
```
### Other Information (e.g. stacktraces, related issues, suggestions how to fix)

Here is the output of a `console.log(Datetime)`:
```
{
    default: ƒ (props, context, updater)
    defaultProps: {className: "", defaultValue: "", inputProps: {…}, input: true, onFocus: ƒ, …}
    moment: ƒ hooks()
    propTypes: {onFocus: ƒ, onBlur: ƒ, onChange: ƒ, onViewModeChange: ƒ, locale: ƒ, …}
}
```
It seems that the component is exported as a `default` export.
If I modify the type definitions to use `export default` then the runtime error goes away:
``` TS
// export = ReactDatetimeClass;
export default ReactDatetimeClass;
```
``` TS
import Datetime from "react-datetime";
```

I'm using the latest version of `react-datetime` and `moment.js`, and I'm compiling my project with `typescript 2.7.1`

Am I doing something wrong, or the type definition should use a `export default`?

**Comment by rikkit** [comment]
This works for me

```
import * as React from "react";
import * as DateTime from "react-datetime";

class extends React.Component {
  render() {
    return (
      <DateTime />
    );
  }
}
```

Which is similar to the README example:

```
import * as Datetime from 'react-datetime';

class MyDTPicker extends React.Component<MyDTPickerProps, MyDTPickerState> {
    render(): JSX.Element {
        return <Datetime />;
    }
}
```

**Comment by szabolcsx** [comment]
@rikkit Which version of `typescript` are you using?

**Comment by rikkit** [comment]
2.6. But I think the issue could be `const Component = () => <Datetime />;` - I haven't seen that usage before. Have you tried just writing `<Datetime />` in your render method?

**Comment by szabolcsx** [comment]
@rikkit Yes, I tried rendering it in a class component as well, with the same result. I don't think it should make a difference as `react` supports both functional and class components:
https://reactjs.org/docs/components-and-props.html#functional-and-class-components

Can you post the contents of your `tsconfig.json` file as well?

**Comment by rikkit** [comment]
Sure. 

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "isolatedModules": false,
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declaration": false,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "sourceMap": true,
    "removeComments": true,
    "noLib": false,
    "preserveConstEnums": false,
    "suppressImplicitAnyIndexErrors": true,
    "outDir": "./lib",
    "importHelpers": true,
    "types": [
      "es6-promise",
      "google.analytics"
    ]
  }
}
```

**Comment by szabolcsx** [comment]
@rikkit Thanks! I had to switch to `commonjs` modules and the error went away.

**Comment by QuantumInformation** [comment]
We get this error using `import * as Datetime from "react-datetime";`

<img width="660" alt="Screenshot 2019-03-11 at 15 20 24" src="https://user-images.githubusercontent.com/216566/54135173-3e305b00-4411-11e9-83b1-766a88b13842.png">

**Comment by itsmichaelwang** [comment]
Hey, not to bump a dead thread, but I was encountering the exact same error message but my root cause was different. I forgot to install moment.js: `yarn install moment`
