### ISSUE TITLE
Make react-datetime compatible with React 16 - Cannot read property input of undefined

### ISSUE THREAD

**Issue by danday74** [YouCanBookMe/react-datetime#527]
This is not a candidate for version 3 but should be.

React 16 currently throwing on DateTime.js ~ln 412 ... DOM.input( ... etc

Cannot read property input of undefined

Please make this package compatible with React 16

**Comment by layneanderson** [comment]
Sorry this isn't enough to go on.  The current version of react-datetime works in React 16 fine for me and others.
