### ISSUE TITLE
Time picker doesnt work

### ISSUE THREAD

**Issue by Dictory** [YouCanBookMe/react-datetime#534]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

1. Latest version react-datetime
2. React 16.2.0
```javascript
<Datetime open value={value} onChange={handler} />
```
### Expected Results

Time picker change time.

### Actual Results

Can\`t change time
![img](https://s1.gifyu.com/images/datetime.gif)

**Comment by layneanderson** [comment]
Cannot reproduce.  Needs additional info.

**Comment by Dictory** [comment]
@layneanderson sorry now alright and i don\`t know why.
