### ISSUE TITLE
Release master to npm so we can use onNavigateBack and onNavigateForward without tagging master

### ISSUE THREAD

**Issue by ralphholzmann** [YouCanBookMe/react-datetime#569]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Steps to Reproduce

1. Try to use `onNavigateBack/onNavigateForward` on latest version (2.14.0)

### Expected Results

1. They fire.

### Actual Results

1. They don't fire.

### Minimal Reproduction of the Problem
These very useful events were merged into master in February, but there hasn't been a release since. Can I kindly nudge you to cut a release so I don't have to tag a git sha in my `package.json`? 😬 😅

**Comment by arqex** [comment]
Done!

Sorry for the delay!

**Comment by ralphholzmann** [comment]
No worries at all. Thank you, and thank you for this great component!
