### ISSUE TITLE
Selecting range of dates

### ISSUE THREAD

**Issue by borovik96** [YouCanBookMe/react-datetime#570]
### I'm Submitting a ...

[ ] Bug report
[x] Feature request
[ ] Support request

Add oppotunity to select date interval ([Example](http://adphorus.github.io/react-date-range/)). It would be nice to have this feature, it could be useful in many cases.

Anyway, thanks you for this lib, I realy love it :heart:

**Comment by arqex** [comment]
Hey @borovik96 

I don't think we'll ever implement the interval picker, but it's not difficult to create one using 2 react-datetimes, I think I've done it sometime but never documented it.

Using 2 components (or one clicked twice), first for the initial date, second for the end date and using [the `renderDay` prop](https://github.com/YouCanBookMe/react-datetime#customize-the-datepicker-appearance) to highlight the selected interval days.
