### ISSUE TITLE
Incorrect `onChange` typings.

### ISSUE THREAD

**Issue by sstarrAtmeta** [YouCanBookMe/react-datetime#572]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Attempting to use typings `DateTime.d.ts`. `onChange` event says it expects a type `Moment | string | ChangeEvent<any>`. This contradicts documentation, and is also different than the pre Typescript 1.8 typings.

### Expected Results
onChange function should be typed to accept `Moment | string` ( change should also be applied to older typings file ).

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
The ChangeEvent appears to have been added as an option in https://github.com/YouCanBookMe/react-datetime/commit/752fa8b2aee6385115c86d74e8f641de48982323

**Comment by arqex** [comment]
Hey @sstarrAtmeta 
It should be fixed in the recently released version 2.15
