### ISSUE TITLE
Add an "id" property for referencing by label

### ISSUE THREAD

**Issue by adamsbloom** [YouCanBookMe/react-datetime#581]
### I'm Submitting a ...
```
[ ] Bug report
[x] Feature request
[ ] Support request
```

I've got a form group that includes text inputs, dropdown lists, and a react-datetime Datetime control. Each of my standard \<input\> controls has an "id" property, and an associated \<label\> control with an "htmlFor" property referencing it. When I click on the label, my cursor automatically goes to the correct text or dropdown box, which may be a small detail, but it's nice.

I would like to propose adding an "id" property to the Datetime control, which then gets passed down into the inner \<input\> control, so that I can easily associate a \<label\> with it.

**Comment by arqex** [comment]
Hey @adamsbloom 

Have a look at the `inputProps` prop in the readme file.
