### ISSUE TITLE
parameter source for onChange method?

### ISSUE THREAD

**Issue by lukezavrel** [YouCanBookMe/react-datetime#591]
Hi, 
is there a possibility to find out the source of the change (meaning if user entered the date by typing it into input or by clicking in the picker)?
Or if there isn't, would it be possible to add that in a parameter for onChange method?
Thanks for your answer.

**Comment by arqex** [comment]
It would add much more complexity to the change tracking. But you can listen to `change` events in the input by using  `inputProps={{ onChange = () => console.log('your tracking here') }}` maybe that way you can detect who is the responsible
