### ISSUE TITLE
Adding a peerdep is semver-major.

### ISSUE THREAD

**Issue by ljharb** [YouCanBookMe/react-datetime#596]
You added a peerdep on moment-timezone in v2.16, which is a minor version. Adding a peerdep is a breaking change.

Please remove the peerdep requirement in a v2.16 patch, as this is breaking our downstream builds.

**Comment by arqex** [comment]
Looks like it finally got slipped in as a peer dependency :(

Sorrt for that. I have just published a new version `2.16.2` that removes the peer dependency and add a runtime warning if `displayTimeZone` prop is used and moment timezone is not loaded.

**Comment by arqex** [comment]
Seems that it finally got slipped into the peerDependecies.

Sorry for that. I have released a new version `2.16.2` that removes the peerDependency and add a runtime warning in the prop `displayTimeZone` is used and moment timezone is not loaded.

**Comment by ljharb** [comment]
Thank you, much appreciated!
