### ISSUE TITLE
Calendar not opening on click/focus

### ISSUE THREAD

**Issue by CWSites** [YouCanBookMe/react-datetime#597]
### I'm Submitting a ...
```
[ ] Bug report
[ ] Feature request
[x] Support request
```

### Steps to Reproduce
1. visit http://stratusphere-ux.appspot.com/inspectors-users (data will not load, that's okay)
2. Change **Date Range** to **Custom**
3. Click in the **Start Date/Time** or **End Date/Time** field and observe that the calendar doesn't display.

### Expected Results
When I Click in the **Start Date/Time** or **End Date/Time** field the calendar should display.

### Actual Results
When I Click in the **Start Date/Time** or **End Date/Time** field the calendar does not appear, and there is no error (fails silently).

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
If I add `open={true}` to one of the fields the calendar displays as expected. This was working for awhile, I'm not sure when it became broken. I verified that I am on the latest version `2.16.2`. 

I was able to track the issue down to `APIContext`, if I remove that it works but I'm stuck after that.

### My code
```
export class Machines extends Component {

toggleStartCalendar = () => {
    this.setState({ showStartCalendar: !this.state.showStartCalendar, showEndCalendar: false })
}

render() {
    return (
        <I18n>
            {(t) => (
                <ContentWrapper>
                    ...
                    <Col lg={ 2 } md={ 6 } sm={ 12 }>
                        <FormGroup>
                            <Label className="control-label">Start Date/Time</Label>
                            <Datetime inputProps={{className: 'form-control'}}
                                      ref="start-date"
                                      closeOnSelect={true}
                                      disableCloseOnClickOutside={false}
                                      defaultValue={parentState.startDate}
                                      onChange={this.updateStartDate}
                                      open={this.state.showStartCalendar}
                                      onBlur={() => this.toggleStartCalendar()}
                                      onFocus={() => this.toggleStartCalendar()}
                            />
                        </FormGroup>
                    </Col>
                    ...
                </ContentWrapper>
            )}
        </I18n>
    );
}}

export default React.forwardRef((props, ref) => (
    <APIContext.Consumer >
        {context => <Machines {...props} apiURL={context.apiURL} ref={ref} />}
    </APIContext.Consumer>
));
```

**Comment by CWSites** [comment]
Something with react context is blocking some of the default functionality. I have been able to rebuild most of it except for the `onClick` not working as it should. If I tab in/out of the field it works as expected however if I click in/out of the field nothing happens.

**Comment by arqex** [comment]
Keep in mind that onBlur and onFocus are not really the event listeners for the events in the input.
Try to use `inputProps={{onBlur, onFocus}}` instead to handle focus when controlling the component.

**Comment by CWSites** [comment]
Thanks @arqex, I was able to get `onClick` working when I put it inside of `inputProps` however now it won't close the calendar when clicking outside of the element. Using `onBlur` inside of `inputProps` closes the calendar when clicking outside, however it also closes the calendar when I click on the calendar itself.
