### ISSUE TITLE
Support for Formik

### ISSUE THREAD

**Issue by mohitmutha** [YouCanBookMe/react-datetime#598]
This control currently does not work with Formik as the onChange event is overridden to always return the moment object. Formik expects a HTML event onChange. 

Any ideas how this can be achieved?

**Comment by joeynguyen** [comment]
You have to use `form.setFieldTouched` for `onBlur` and `form.setFieldValue` for `onChange`.

I created a custom wrapper component named `FormikDateTime` to handle it.

This is how I call it:

```
<label htmlFor="date">Date</label>
<Field name="date" timeFormat={false} component={FormikDatetime} />
```

```import React from 'react';
import Datetime from 'react-datetime';
import moment from 'moment';

const DATE_FORMAT = 'MM-DD-YYYY'

const FormikDateTime = ({ field, form, timeFormat }) => {
  const onFieldChange = value => {
    let dateValue = value;

    // if the date field isn't in a valid date format,
    // react-datetime's onChange handler returns a string
    // otherwise it returns a moment object
    // this is why we can't override DateTime's onChange
    // prop with Formik's field.onChange
    if (value instanceof moment) {
      dateValue = moment(value).format(DATE_FORMAT);
    }

    form.setFieldValue(field.name, dateValue);
  }

  const onFieldBlur = () => {
    form.setFieldTouched(field.name, true);
  }

  return (
    <Datetime
      dateFormat={DATE_FORMAT}
      timeFormat={timeFormat}
      id={field.name}
      name={field.name}
      onChange={onFieldChange}
      onBlur={onFieldBlur}
    />
  );
}

export default FormikDateTime;
```

The `id` and `name` props passed to the DateTime component currently don't seem to be doing anyt
hing though.  I added them in hopes of that they'll be passed along to the <input /> component in the future.

This is as of "react-datetime": "2.16.2" and "formik": "1.3.2".

**Comment by arqex** [comment]
@joeynguyen  That's a great response! 

react-datetime is not just an input, the `onChange` event is not triggered always by updating the input (there might be triggered by clicks) and that's why it can't return a consistent input change event.

With the nice response above I can close this

**Comment by TheEricBurnett** [comment]
@joeynguyen Thanks for posting your Formik implementation! By the way, if you'd still like to pass `name`, `id`, or any other props to the `<input />`, you can do that like this:

```javascript
<DateTime
    inputProps={{
        name: 'saved',
        id: 'saved',
        ...anyOtherProps
    }}
/>
```

**Comment by joeynguyen** [comment]
@TheEricBurnett awesome thanks for the tip!
