### ISSUE TITLE
Uncaught TypeError: onClickOutside is not a function

### ISSUE THREAD

**Issue by daltonwignall** [YouCanBookMe/react-datetime#599]
Hey all!

I've been struggling through a problem the past few days with bundling the react-datetime component after transitioning our component library to bundle with rollup. I'm getting the following error in the console when launching our dev environment pointing to the bundled js containing the react-datetime component:
![image](https://user-images.githubusercontent.com/4975078/48216147-851a2100-e349-11e8-8fa2-6bf2936d75d2.png)

This points to the following line within my bundle:
![image](https://user-images.githubusercontent.com/4975078/48216246-c14d8180-e349-11e8-88e0-0298be8e2322.png)

If I remove the `.default` portion here it fixes the issue and the datepicker successfully loads along with our other components. Likewise, removing the `.default` portion from the file [here](https://github.com/YouCanBookMe/react-datetime/blob/master/DateTime.js#L9-L10), (I'm assuming this is where the bundled line comes from?) also fixed the issue for me.

It appears my problem is very similar to the fixed issue I [here](https://github.com/YouCanBookMe/react-datetime/issues/395) but rather I'm having the inverse problem. The versions **prior** to `2.10.3` work fine for me when bundled, but break after the changes made [here](https://github.com/YouCanBookMe/react-datetime/pull/434/files) which are included in every version **after** `2.10.2`.

If it helps at all, this is my rollup config below
```js
import autoprefixer from "autoprefixer";
import { uglify } from "rollup-plugin-uglify";
import postcss from "rollup-plugin-postcss";
import resolve from "rollup-plugin-node-resolve";
import babel from "rollup-plugin-babel";
import builtins from "rollup-plugin-node-builtins";
import commonjs from "rollup-plugin-commonjs";

const rollupConfig = {
  input: "lib/react/index.js",
  output: {
    file: `dist/bundle.min.js`,
    format: "umd",
    name: "exampleLibraryName",
    globals: {
      react: "React",
      "react-dom": "ReactDOM",
      "prop-types": "PropTypes",
    },
  },
  external: [
    "react",
    "react-dom",
    "prop-types",
  ],
  plugins: [
    commonjs(),
    builtins(),
    babel({
      exclude: "node_modules/**",
    }),
    resolve({
      extensions: [".js", ".jsx"],
    }),
    postcss({
      sourceMap: true,
      plugins: [autoprefixer],
      extract: "dist/styles.min.css",
      minimize: true,
    }),
  ]
};

export default rollupConfig;
```

Am I missing something in the way I'm bundling this, or is this a bug? Any guidance/thoughts are hugely appreciated.

**Comment by arqex** [comment]
Hey, this is the typical problem of mixing different module types.

I don't know what's your babel/webpack configuration, but it you have set it up to use ES6 modules ( to use the `import` and `export` words in your code ), you will need to use the `.default` part in commonjs or umd ones ( the ones that use `module.exports` ).

If you are loading the version of react-datetime that is in the `/dist` folder you will need to add that ugly `.default` prefix. If you load the library by using `import Datetime from 'react-datetime'` you shouldn't see that problem.

**Comment by daltonwignall** [comment]
Hey @arqex thanks for the reply unfortunately we are importing it via ```import Datetime from "react-datetime";``` as you mentioned above and still receiving the above error after bundling.

Any further ideas?

**Comment by arqex** [comment]
Sorry for the delay replying.

Since we don't know if that "umd" module packaging will get the commonjs or the es6 module, maybe you can add an alias in your bundler configuration to import the distribution version of react-datetime. Something like:

```
resolve: {
    alias: {
      'react-datetime: './node_modules/react-datetime/dist/react-datetime.js'
    }
  }
```

Not sure about how to se the path correclty, but I hope you get the point.

**Comment by daltonwignall** [comment]
Unfortunately I'm still running into a similar issue when aliasing to the dist version.

![image](https://user-images.githubusercontent.com/4975078/51481353-4ba65e80-1d59-11e9-9ba9-0e715d6abe6a.png)

I used the `rollup-plugin-alias` module for handling the aliasing (Unless there is another way to do aliasing that I'm missing?)

Here is my rollup config:
```js
import autoprefixer from "autoprefixer";
import { uglify } from "rollup-plugin-uglify";
import postcss from "rollup-plugin-postcss";
import resolve from "rollup-plugin-node-resolve";
import babel from "rollup-plugin-babel";
import builtins from "rollup-plugin-node-builtins";
import commonjs from "rollup-plugin-commonjs";
import alias from "rollup-plugin-alias";

const rollupConfig = {
  input: "lib/react/index.js",
  output: {
    file: "dist/bundle.min.js",
    format: "umd",
    name: "metaComponents",
    globals: {
      react: "React",
      "react-dom": "ReactDOM",
      "prop-types": "PropTypes",
    },
  },
  external: [
    "react",
    "react-dom",
    "prop-types",
  ],
  plugins: [
    babel({
      exclude: "node_modules/**",
    }),
    alias({
      "react-datetime": "node_modules/react-datetime/dist/react-datetime.js"
    }),
    commonjs(),
    builtins(),
    resolve({
      extensions: [".js", ".jsx"],
    }),
    postcss({
      minimize: true,
      sourceMap: true,
      plugins: [autoprefixer],
      extract: "dist/styles.min.css",
    }),
    uglify(),
  ]
};

export default rollupConfig;
```

Thanks again for all your help/thoughts!
