### ISSUE TITLE
It seems not to support IE8

### ISSUE THREAD

**Issue by skchen28** [YouCanBookMe/react-datetime#606]
Clickoutside seems don't work in browser of IE8.I have to suuport IE8 because of users.Can you give me some advice.Thank you very much.

**Comment by arqex** [comment]
I think it's something really hard to achieve. react-datetime is using react-onclickoutside to handle those clicks, and if IE8 doesn't follow the modern event standards it might fail on checking those clicks. Maybe you can raise the issue in https://github.com/Pomax/react-onclickoutside
