### ISSUE TITLE
is there locale for Hebrew? 

### ISSUE THREAD

**Issue by guymalka** [YouCanBookMe/react-datetime#608]
any locale for Hebrew?
he-IL not work, how can i create locale?

### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[ ] Support request
```

**Comment by arqex** [comment]
Sure, have a look at the i18n docs, you can set any locale:

https://github.com/YouCanBookMe/react-datetime/blob/master/README.md#i18n

**Comment by guymalka** [comment]
i dont see how to change the language in link
