### ISSUE TITLE
BC break in 2.10.3

### ISSUE THREAD

**Issue by ujovlado** [YouCanBookMe/react-datetime#611]
Due to upgrade of `react-onclickoutside` (from 5 to 6), version  2.10.3 broke compatibility.

So, it is not true that this library is compatible with React 13+, beacause `react-onclickoutside` needs newer version.

**Comment by arqex** [comment]
HI @ujovlado 

Thanks for raising this problem and sorry for any inconvenience. Unfortunatelly we are going to keep using the latest version of react-onclickoutside, that means that we are not suporting react 13 anymore.

We are working on the version 3 of the library right now and all the dependencies will be updated. If you need support for react 13 you need to get stuck in order versions of the library.

**Comment by ujovlado** [comment]
yes, but problem is that this information:

https://github.com/YouCanBookMe/react-datetime/blob/2a83208452ac5e41c43fea31ef47c65efba0bb56/package.json#L44-L45

is not true.

I think you should update it to version that matches react-onclickoutside, even if you don't plan to introduce major version with this change
