### ISSUE TITLE
Time picker always set to 8pm if `dateformat` is false and string includes a date

### ISSUE THREAD

**Issue by NathanShi** [YouCanBookMe/react-datetime#612]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Use following code:
```
<DateTime utc={true} strictParsing={false} dateFormat={false} />
```

Note that the value passed in is a string like `2019-01-01T16:00:00.000Z` that previously submitted by the same datetime picker here. We need a utc format in the database.

### Expected Results

The input field display time that is converted to local time.

### Actual Results

The hour is always set to `8pm`

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
Checked on the code itself. Seems it related to the following lines of code:
https://github.com/YouCanBookMe/react-datetime/blob/2a83208452ac5e41c43fea31ef47c65efba0bb56/DateTime.js#L396-L402

The format is default `h:mm A`, however when converting to moment object the we got

![image](https://user-images.githubusercontent.com/22336965/50918581-40247080-1406-11e9-8253-7e870c234538.png)

If we use format `YYYY-DD-MM h:mm A`

![image](https://user-images.githubusercontent.com/22336965/50918609-56323100-1406-11e9-8788-6279eed64cac.png)

The difference is the `_d` field in the object. However we'd like to use as a time picker so I cannot pass in a date format to used here.

**Comment by NathanShi** [comment]
Added the following code for a walk around, update redux form value before it passes to `react-datetime` package to only have time values.
 
```
componentDidMount() {
    var updatedTime = moment.utc(this.props.time, 'YYYY-MM-DD HH:mm', false);
    if (updatedTime.isValid()){
      this.props.dispatch(change('form', 'time', updatedTime.local().format('HH:mm')));
    }
  }

```

If the package can include a default date format for parsing the utc date string that would be great.

**Comment by arqex** [comment]
Hi @NathanShi 

Good catch, but I am not sure it's a bug. In react-datetime, the date and time formats are used for multiple purposes:
 * To show the date as a string in the input box.
 * To parse the value of the input box when the user update it by typing.
 * To parse the value passed as a prop.

The reason for using it all the way around is that the user can update the input, the value goes out and can enter the date picker again using the same validation all the time.

In your case, the value format (UTC) and the parsing format don't match. You can pre process the string to adapt it to the expected time format, and lose the date info, or just use dates as the value input:

```
<DateTime utc={true} strictParsing={false} dateFormat={false} value={ new Date("2019-01-01T16:00:00.000Z") } />
```

**Comment by NathanShi** [comment]
@arqex Thanks for your response. I agree that the date shouldn't be a string on the backend. Unfortunately, we have to deal with it that way based on requirements. I'm closing the issue as we can manipulate the value before we pass to the datetime component. Thanks again.
