### ISSUE TITLE
what does the onViewModeChange do?

### ISSUE THREAD

**Issue by macarole** [YouCanBookMe/react-datetime#615]
### I'm Submitting a ...

```
[x] Bug report
[ ] Feature request
[x] Support request
```

### Steps to Reproduce
```
// first create an react application,based on create-react-app
// then put content below in a file(need moment library additionaly )
//i want to set the default value only for the time,but the defaultValue won't work.
//so i consider to set the timeFormat prop,eg timeFormat={'23:59:59'},but i don't want to set it a contant value,
//once it change to time view mode ,the timeFormat should alter accordingly,eg timeFormat={'HH:mm:ss'}
//then i use the onViewModeChange to change the viewMode so as to alter the timeFormat accordingly.
//as a result of that,the date i selcted in default viewmode won't alter the header time in time viewmode
//is there anything i can do now?
import React, { Component } from "react";
import "react-datetime/css/react-datetime.css";
import Datetime from "react-datetime";
import "moment/locale/zh-cn";
const timeFormat = {
  normal: "HH:mm:ss",
  end: "23:59:59"
};
class App extends Component {
  constructor(props) {
    super(props);
    this.onViewModeChange = this.onViewModeChange.bind(this);
    this.state = {
      hasEnterTimeView: false
    };
  }
  onViewModeChange(viewmode) {
    if (viewmode === "time") {
      this.setState({
        hasEnterTimeView: true
      });
    }
  }
  render() {
    return (
      <div className="App">
        测试时间
        <Datetime
          onViewModeChange={this.onViewModeChange}
          timeFormat={!this.state.hasEnterTimeView && timeFormat.end}
        />
      </div>
    );
  }
}

export default App;
```

### Expected Results
 run the code above,and you should find the issue

### Actual Results
no

### Minimal Reproduction of the Problem
"moment": "^2.20.1",
    "react": "^16.7.0",
    "react-datetime": "^2.14.0",

**Comment by arqex** [comment]
I think you are confusing the format with the value. In this cases that you want to control the dates it's better to use the component in a controlled way (it's always better to control the component's value):
https://codepen.io/anon/pen/OdPBgO

**Comment by macarole** [comment]
@arqex 
Thank you for your demo. But maybe I didn't describe it clearly and make you misunderstood . This is the case that I don't want to set the default datetime value. but want to set the default time (not including date) to 23:59:59 When I open that date space.i tried to refer to the document,but nothing found to set the default time.So I am trying to see if I can fix some digital values ​​in the timeFormat. I found that if I did  that, I can directly set the default value of the hour, minute and second. However, if the timeFormat is set to fixed decimal values (eg 23:59:59), once  really want to reselect the minutes and seconds, i failed. So I intend to use onViewModeChange to dynamically change the value of timeFormat when viewMode is time, in order to achieve the default value of setting time, minute and second, without affecting the effect of resetting time and seconds. I am sorry that my English is not very good. This is google translation. You can run my code to help me see what happened.

**Comment by lakshmisanthi** [comment]
Thank you. Demo is save my day.
