### ISSUE TITLE
Solved an issue where React component state wasn't updating after selecting month/day/year

### ISSUE THREAD

**Issue by Salmonster** [YouCanBookMe/react-datetime#62]
I almost abandoned this add-on until I figured out how to get around an issue where a component state wasn't updating its month, day, or year state values which I had tied to the present selection of the datetime picker. I would have to select a given day/month/year twice in order for it to update the state appropriately; but strangely, not for the time selector, which updated the time state value immediately. The workaround in the code is to pass the moment object from one callback to another for the state to update. You can see an example in my code [here](https://github.com/GitCats/BluePlate/blob/master/client/views/ownerProfile.jsx) in the CreateDeal class, specifically in the chooseDate and postDeal functions. Big thanks to @arqex for responding to my general inquiry regarding the matter when I was trying to figure it out.

**Comment by simeg** [comment]
I'm not sure what to do with this.. maybe add something to the docs?

What do you think @arqex?

**Comment by simeg** [comment]
Useful information, but a bit too general to squeeze in to the documentation (from my understanding). I'll label it and close it.
