### ISSUE TITLE
Please remove use of namespaces or it doesn't work with babel typescript

### ISSUE THREAD

**Issue by QuantumInformation** [YouCanBookMe/react-datetime#625]
### I'm Submitting a ...

```
[ x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Use the component in a new CRA app with typescript `npx create-react-app my-app --typescript
`

### Actual Results

App fails to compile as component uses Namespaces which are not supported in babel - typescript.

**Comment by rikkit** [comment]
How are you including `react-datetime`? Are you using npm? Standard practice is to not compile your dependent libraries - but use the bundled plain JS file.

**Comment by QuantumInformation** [comment]
Thanks,

we switched
` import * as Datetime from 'react-datetime';`

 to 

`import Datetime from 'react-datetime';`
