### ISSUE TITLE
maintainer.

### ISSUE THREAD

**Issue by export-mike** [YouCanBookMe/react-datetime#66]
Hey,

notice the comment in the read me. so the reason you can't maintain this because you've moved on and have no time to maintain? 

are you now using an alternative?

I've taken a local fork of this in my own project atm.

**Comment by arqex** [comment]
Hi @export-mike 

Thanks for you interest in react-datetime. Good news: youcanbook.me is sponsoring this project so updates will come more often from now on.

Anyways if you make some progress in your fork and you think it can be merge with react-datetime do not hesitate to PR. If they are nice, we can discuss if you'd like to be a maintainer of the project.

Cheers

**Comment by export-mike** [comment]
cool thanks!
