### ISSUE TITLE
alignment of picker off screen when input near edge

### ISSUE THREAD

**Issue by crobinson42** [YouCanBookMe/react-datetime#662]
```
react@16.11.0 
react-dom@16.11.0
react-datetime@2.16.3
```

![image](https://user-images.githubusercontent.com/5973579/67890082-41499a00-fb0d-11e9-881f-0c19e6d62b2a.png)

**Comment by felipecarrillo100** [comment]
You can easily solve that with CSS.
Add a class to the component,  then in your css file add the class properties. Making right:0 will solve your problem.
```
.mycustomclass {
right:0
}
```
