### ISSUE TITLE
Need to Display Both Date and Time together

### ISSUE THREAD

**Issue by PuneetSivananda** [YouCanBookMe/react-datetime#665]
Hi,
I am looking to add both the Data and the Time Selector together, I need to be able to Enable Both the Date Selector as well as the Time Selector together when you click the DateTime Text Box

**Comment by bsantos09** [comment]
Hi how did you solve this? Any pointers? @PuneetSivananda

**Comment by PuneetSivananda** [comment]
Hey I had to Write a Custom Callback Function for this use case

Used 3 text input boxes for HH:MM:SS

Used the DatePicker on top these text boxes to display the date picker

Capture the  hh:mm:ss from the input boxes and Date Value 

Append these Values and return on a Custom  Submit  button onClick functionality
