### ISSUE TITLE
componentWillReceiveProps Warnings cluttering console - please either rename it to UNSAFE_componentWillReceiveProps or swap them to componentDidUpdate

### ISSUE THREAD

**Issue by afcjunior** [YouCanBookMe/react-datetime#673]
Version used: 2.16.3

### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[X] Support request
```

### Steps to Reproduce

1. import DateTime from 'react-datetime';2. Use the component (I passed it Onchange, defaultValue and inputProps, althought I don't believe this matters).

### Expected Results

It should work without warnings.

### Actual Results

It works but displays a warning on my console:

Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

**Comment by felipecarrillo100** [comment]
Seems a dupplicate of #671

**Comment by jaagupku** [comment]
Duplicate of #649

**Comment by arqex** [comment]
Yes, duplicated of https://github.com/YouCanBookMe/react-datetime/issues/649

It's going to be fixed in v3
