### ISSUE TITLE
componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by julianpetriv** [YouCanBookMe/react-datetime#678]
### I'm Submitting a ...

```
[ ] Bug report
[x] Feature request
[ ] Support request
```

### Steps to Reproduce
Use Datetime component
### Actual Results
I have a warning that componentWillReceiveProps is not recommended to use

### Minimal Reproduction of the Problem

componentWillReceiveProps is deprecated so you should rewrite code to use new methods of lifecycle

**Comment by arqex** [comment]
Duplicated - https://github.com/YouCanBookMe/react-datetime/issues/649
Going to be fixed in v3
