### ISSUE TITLE
disableCloseOnClickOutside is not working with react-datetime v 3.0.0 and  react v16.12.0 , react-dom v16.11.0

### ISSUE THREAD

**Issue by gauravjain811** [YouCanBookMe/react-datetime#685]
### I'm Submitting a ...

```
[x ] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce

Click on calendar to launch modal, then click outside
### Expected Results

 It should close modal for calendar
### Actual Results

It's not closing modal for calendar
### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 

By setting disableCloseOnClickOutside as false is not fixing for react-datetime v 2.16.3 or 
https://cdnjs.cloudflare.com/ajax/libs/react-datetime/3.0.0/react-datetime.min.js  and 
react v16.12.0 
react-dom v16.11.0

Solution: disableCloseOnClickOutside  is not registered as default props, by registering it might fix this issue. Please do the needful.
![image](https://user-images.githubusercontent.com/14151045/74724833-ea560500-5262-11ea-9e91-aee2977e2a6f.png)

**Comment by gauravjain811** [comment]
I fixed it by registering 'disableCloseOnClickOutside ' in default props. Please merge in master branch and do the needful.

**Comment by arqex** [comment]
Hey @gauravjain811 ,

`disableCloseOnClickOutside` has been renamed to `closeOnClickOutside` in v3 to avoid double negations.

Please use `closeOnClickOutside={false}` in order to make your app not to close the calendar on clicking outside.

**Comment by bvanhou** [comment]
Any updates on this?
