### ISSUE TITLE
Outdated documentation and import problems

### ISSUE THREAD

**Issue by JMPiechowiak** [YouCanBookMe/react-datetime#686]
### I'm Submitting a ...

```
[ ] Bug report
[ ] Feature request
[ x ] Support request
```

### Steps to Reproduce

I was using version 3.0.0-beta.4 and everything was working fine.
After upgrading all major packages in the project (including react and moment.js) to newest version I also wanted to upgrade react-datetime so I installed 3.0.0-beta.7 version.

My import looks like this:
`import Datetime from 'react-datetime';`

And I render Datetime component with some props like this:
```
    <Datetime
       value={filter && filter.value ? filter.value.from : ""}
      onChange={value => onChange({
        from: value,
        to: filter && filter.value && filter.value.to ? filter.value.to : ""
      })}
      inputProps={{ placeholder: t('from') }}
      locale={t("language_code_for_moment")}
    />
```

### Expected Results

Everything should work like it did before on  3.0.0-beta.4
### Actual Results

I got some weird import errors
![error](https://user-images.githubusercontent.com/22665005/74753444-6c98f600-5270-11ea-9ac4-b723ec125138.png)

### Other Information (e.g. stacktraces, related issues, suggestions how to fix)
 
I've tried to change my code like documentation suggested:
```
require('react-datetime');
 
...
 
render: function() {
    return <Datetime />;
}
```
But it doesn't seem to work.

Also I tried to import styles like:
`import 'react-datetime/css/react-datetime.css'`

But it doesn't help too.

**Comment by davidcostadev** [comment]
@JMPiechowiak are you using webpack? Could you show the rule of import css? Of if not, could you show where you add the config to import css?

**Comment by gauravjain811** [comment]
pls try using import Datetime from 'react-datetime'; => import * as Datetime from 'react-datetime';

**Comment by arqex** [comment]
I think the missing CSS file is related to this error in the beta.7 https://github.com/YouCanBookMe/react-datetime/pull/683

I'll review that PR and try to release a new version that would fix it

**Comment by arqex** [comment]
I have just released the beta.8 for v3. It should fix the CSS import problem. Just update and 
```
import 'react-datetime/css/react-datetime.css`
```
