### ISSUE TITLE
If timeFormat equals 'LT' timepicker is missing

### ISSUE THREAD

**Issue by somename85** [YouCanBookMe/react-datetime#69]
If timeFormat equals 'LT' we can go to timepicker tab, bul it is empty.

**Comment by somename85** [comment]
http://codepen.io/somename85/pen/WwoWLW

**Comment by jiminycricket** [comment]
'LT' is not a useable timeFormat, which is a Localized formats, you could try use 'HH', 'mm' or 'hh/m', all valid setting can check on this [link](http://momentjs.com/docs/#/displaying/format/)

**Comment by somename85** [comment]
It will be nice to update the docs that using Localized formats for timeFormat does not supports.
Also it is strange, because  Localized formats works fine with dateFormat.

**Comment by simeg** [comment]
Added clarification to documentation in commit https://github.com/YouCanBookMe/react-datetime/commit/1de42c583b743fbd981af9ff9584fa6845ce6828.
