### ISSUE TITLE
Time picker in HH format

### ISSUE THREAD

**Issue by giorgi-m** [YouCanBookMe/react-datetime#703]
### I'm Submitting a ...

```
[ ] Bug report
[ x ] Feature request
[ x ] Support request
```

### Steps to Reproduce
~~In below screenshot~~

![Screenshot from 2020-06-11 11-23-33](https://user-images.githubusercontent.com/41240312/84356700-a1410c80-abd5-11ea-82ac-7efd2abe344d.png)

~~I can't find a config, which would allow me to select the time using 24 hour format, without the AM/PM, is this possible?~~

---

I think I found the right props:

` timeFormat="HH:mm" `
 
Just now it shows the hour digit **only as a single letter** as below:

![Screenshot from 2020-06-11 16-51-48](https://user-images.githubusercontent.com/41240312/84386931-3f979700-ac03-11ea-889f-8538c8bfc9b9.png)

Can we make it shows HH format? Like with minutes?

**Comment by alfficcadenti** [comment]
any news on this?
