### ISSUE TITLE
closeOnSelect is not working if I set the value property

### ISSUE THREAD

**Issue by khajonpot** [YouCanBookMe/react-datetime#71]
In updateSelectedDate function, the closeCalendar will run if I set "undefined" to value property.
It would be great if the closeCalendar can run based on closeOnSelect even if the value is set. So, I don't need to call closeCalendar manually.

[Edit]
Oops, sorry I just found that I should declare "open" property to force it close all the time.

**Comment by simeg** [comment]
I will close this as the author seems to have resolved his/her issue (looking at the edit comment).
