### ISSUE TITLE
Date or Time only

### ISSUE THREAD

**Issue by crobinson42** [YouCanBookMe/react-datetime#75]
I would like to request a feature. The ability to only allow date or time on the picker, ie:

```
<DateTime
  mode='time'
/>
```
This would also set the `viewMode` to the same `mode` if passed.

The default `mode` would obviously be `datetime` with the options of `date` or `time`.

I'm glad to assist with contribution guidelines.

**Comment by arqex** [comment]
Hi @crobinson42 

You already can use the picker only for time or date using `dateFormat={false}` or `timeFormat={false}`.

http://codepen.io/arqex/pen/eZyZBe

Cheers,
Javi

**Comment by ryanhca** [comment]
@arqex fyi that codepen has issues/Is not rendering/is not complete.

**Comment by simeg** [comment]
@ryanhca in what way? It's working for me. It might be a bit hard to see since the input field is missing a border.

**Comment by ryanhca** [comment]
@simeg I see it now haha! Sorry!

**Comment by simeg** [comment]
@ryanhca no worries, I thought the same thing the first time I saw it :)
