### ISSUE TITLE
How to edit seconds or milliseconds?

### ISSUE THREAD

**Issue by Renaud009** [YouCanBookMe/react-datetime#81]
As introduction, you say the library "allows to edit even date's milliseconds." I don't see any example or any more mention about seconds nor milliseconds.

Can you provide me a code example?

Thank you in advance and good job

**Comment by arqex** [comment]
Hey, sorry for the late reply.

To activate the millisecond edition just use a `timeFormat` prop that displays the milliseconds:

`timeFormat="H:mm:ss.SSS"`

See http://momentjs.com/docs/#/displaying/format/

**Comment by Pana** [comment]
I have set the timeFormat see the millisecond edit input, but the value can't edit

**Comment by irenekovalchuk** [comment]
@Pana hey!

Is there a chance you've found a workaround for this issue? Unfortunately, it is still relevant 🙁
