### ISSUE TITLE
Simulate issue

### ISSUE THREAD

**Issue by idoo** [YouCanBookMe/react-datetime#86]
Thank you for a good fork!

How i can simulate 'change' event on this component wit TestUtils or Enzyme?

`wrapper.find('input').simulate('change')` not trigger onChange event for this component

any ideas?

**Comment by arqex** [comment]
Hey, nice question. Sorry for the delay replying.

I would go calling directly the onChange handler like this:

```
// Declaring your component
<Datetime ref="picker" />

// In your tests
this.refs.picker.props.onChange(/* some moment object */);
```

**Comment by layneanderson** [comment]
Closing due to age (> 1 year old).
