### ISSUE TITLE
I want to reduce the size of the Calendar

### ISSUE THREAD

**Issue by ItsMrAkhil** [YouCanBookMe/react-datetime#88]
Is it possible? If yes, Please let me know.

**Comment by davidfurlong** [comment]
You mean the dimensions?

**Comment by akhilpab** [comment]
Dimensions only

**Comment by davidfurlong** [comment]
You're welcome to customize the css in any way you choose, but I doubt that
this will be supported in this repo. See
https://github.com/YouCanBookMe/react-datetime/blob/master/css/react-datetime.css

**Comment by arqex** [comment]
As @davidfurlong said, ( thanks david ), changing the size of the component is as simple as ovewritting CSS rules.
