### ISSUE TITLE
Unable to chose 12PM in Time picker

### ISSUE THREAD

**Issue by eddievagabond** [YouCanBookMe/react-datetime#92]
I am unable to choose 12 PM when choosing only time. If the DateTime component shows 12:00 AM and I choose it, my input displays 12:00PM. If I choose 00:00 AM, I am able to choose 12:00 AM. Am using an incorrect time format?

```
<DateTime
  value={this.props.endTime}
  dateFormat={false}
  timeFormat="h:mm A"
  closeOnSelect={true}
  className="sm"
  viewMode="time"
  onChange={(e, n) => this.props.onDateChange(e, 'endTime')}
  />
```

**Comment by eddievagabond** [comment]
Fixed with this pull request.
https://github.com/YouCanBookMe/react-datetime/pull/93

**Comment by simeg** [comment]
This should be closed.
