### ISSUE TITLE
Add custom steps for time increase/decrease buttons

### ISSUE THREAD

**Issue by loris** [YouCanBookMe/react-datetime#99]
It would be pretty handy (and a requirement in a project i'm working on) to be able to pass as props custom "steps", ie. clicking on the increase button would increment the time by custom interval (15 minutes for instance) instead of just `+1`. I can push a PR with the changes if this is something useful (any recommendation on the props naming?), otherwise I will need to fork it.

**Comment by loris** [comment]
I gave it a go over there: https://github.com/YouCanBookMe/react-datetime/pull/100 (and went a bit further to allow setting min, max and pad values too)

**Comment by mattgi** [comment]
👍 this would be awesome. The PR seems to need a rebase though and I couldn't get your fork to work locally.. any tips on how to get it up and running @loris?

This should work, correct?
```
      <DateTime
        value      = { this.props.data[field.name] }
        onChange   = { this.onChange }
        onBlur     = { this.onBlur }
        dateFormat = { 'Do MMM YYYY' }
        timeFormat = { 'h:mma' }
        minutes    = { { step : 15 } }
      />
```

**Comment by loris** [comment]
@mattgi I just rebased & updated my PR with some suggestions from @arqex 
All the new stuff is in the `timeConstraints` prop now, so you should use it this way:

```
<DateTime
        value              = { this.props.data[field.name] }
        onChange           = { this.onChange }
        onBlur             = { this.onBlur }
        dateFormat         = { 'Do MMM YYYY' }
        timeFormat         = { 'h:mma' }
        timeConstraints    = { { minutes: { step : 15 } } }
      />
```

**Comment by simeg** [comment]
Closing this as PR #100 was merged.
